Repository spacetelescope/drizzlepac, pull requests merged in 2018-05, with the labels that each got.

#131 Revert "EXP: updating package imports"
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/findobj.py
  drizzlepac/tweakutils.py
  setup.py
Labels: bug

#135 Fix C compile warnings
  src/arrdrizmodule.c
  src/cdrizzlemap.c
Labels: bug, code cleanup

#136 Improved documentation to eliminate build warnings
  CHANGELOG.rst
  doc/source/CHANGELOG.rst
  doc/source/LICENSE.rst
  doc/source/conf.py
  doc/source/index.rst
  drizzlepac/ablot.py
  drizzlepac/acsData.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/buildmask.py
  drizzlepac/buildwcs.py
  drizzlepac/catalogs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/findobj.py
  drizzlepac/imageObject.py
  drizzlepac/imagefindpars.py
  drizzlepac/imgclasses.py
  drizzlepac/irData.py
  drizzlepac/linearfit.py
  drizzlepac/mapreg.py
  drizzlepac/mdriz.py
  drizzlepac/mdzhandler.py
  drizzlepac/minmed.py
  drizzlepac/nicmosData.py
  drizzlepac/outputimage.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/processInput.py
  drizzlepac/quickDeriv.py
  drizzlepac/refimagefindpars.py
  drizzlepac/regfilter.py
  drizzlepac/resetbits.py
  drizzlepac/runastrodriz.py
  drizzlepac/sky.py
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/stisData.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/tweakutils.py
  drizzlepac/updatehdr.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
  drizzlepac/wcs_functions.py
  drizzlepac/wfc3Data.py
  drizzlepac/wfpc2Data.py
Labels: Documentation, code cleanup, enhancement

#137 Remove extraneous file
  debug.notes
Labels: code cleanup

#138 Reduce C compile warnings
  src/arrdrizmodule.c
  src/cdrizzleblot.c
Labels: code cleanup

#139 Switch order of includes in C to eliminate _POSIX_C_SOURCE warning
  src/cdrizzleio.c
Labels: code cleanup, enhancement

#134 Update setup version requirement for stsci.image
  setup.py
Labels: bug

#142 Sphinx brain
  doc/source/conf.py
  setup.py
Labels: Documentation, enhancement

#141 mdriz: Fix broken imports
  drizzlepac/mdriz.py
Labels: bug

#144 Add CHANGELOG entry for setup improvement
  CHANGELOG.rst
Labels: Documentation

#145 Create median does not print image background value
  CHANGELOG.rst
  drizzlepac/createMedian.py
Labels: bug

#147 Improve visual of the drizzlepac logs. Log full configobj
  drizzlepac/astrodrizzle.py
  drizzlepac/imgclasses.py
  drizzlepac/tweakreg.py
  drizzlepac/util.py
Labels: enhancement

#132 Improve setuptools overrides and JenkinsFile
  Jenkinsfile
  README
  README.md
  setup.py
Labels: bug, enhancement

#148 Allow use of DEBUG logging level in drizzlepac
  CHANGELOG.rst
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/catalogs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/imageObject.py
  drizzlepac/imgclasses.py
  drizzlepac/linearfit.py
  drizzlepac/outputimage.py
  drizzlepac/processInput.py
  drizzlepac/resetbits.py
  drizzlepac/sky.py
  drizzlepac/staticMask.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/tweakutils.py
  drizzlepac/updatehdr.py
  drizzlepac/util.py
  drizzlepac/wcs_functions.py
Labels: bug
