Repository spacetelescope/drizzlepac, pull requests merged in 2018-04, with the labels that each got.

#124 Prepare 2.2.0
  Jenkinsfile
  MANIFEST.in
  doc/source/release_notes.rst
  setup.py
Labels: enhancement

#125 Fixes to let WFPC2 data process
  doc/source/release_notes.rst
  drizzlepac/processInput.py
  drizzlepac/runastrodriz.py
  drizzlepac/wfpc2Data.py
Labels: bug

#126 Fix input file bug in TweakReg
  doc/source/release_notes.rst
  drizzlepac/tweakreg.py
Labels: bug

#127 Update README
  README
  doc/source/release_notes.rst
Labels: Documentation
