Repository spacetelescope/drizzlepac, pull requests merged in 2018-03, with the labels that each got.

#104 Fix sectioning algorithm in Create Median step
  doc/source/release_notes.rst
  lib/drizzlepac/createMedian.help
  lib/drizzlepac/createMedian.py
Labels: bug

#107 Update minmed code
  lib/drizzlepac/createMedian.py
  lib/drizzlepac/minmed.py
Labels: bug, enhancement

#108 Fix function parameter names
  lib/drizzlepac/createMedian.py
  lib/drizzlepac/minmed.py
Labels: bug

#110 Fix a bug in computation of readnoise_file in minmed
  lib/drizzlepac/minmed.py
Labels: bug

#112 Make astrodrizzle and tweakreg load defaults from package instead of user's local .teal
  lib/drizzlepac/astrodrizzle.py
  lib/drizzlepac/tweakreg.py
Labels: bug, enhancement

#115 Swap defaults for configobj
  doc/source/release_notes.rst
  lib/drizzlepac/astrodrizzle.help
  lib/drizzlepac/astrodrizzle.py
  lib/drizzlepac/tweakreg.help
  lib/drizzlepac/tweakreg.py
  lib/drizzlepac/util.py
Labels: enhancement

#118 Fix Windows build failure
  setup.py
Labels: bug

#119 Replace final __vdate__ reference
  drizzlepac/tweakreg.py
Labels: bug

#121 Allows python2.7 to build; Fixup PEP8
  setup.py
Labels: bug

#120 Add BSD 3-Clause license
  LICENSE.txt
Labels: enhancement

#122 Initial commit of Jenkinsfile
  Jenkinsfile
Labels: enhancement
