Repository spacetelescope/drizzlepac, pull requests merged in 2019-11, with the labels that each got.

#471 Fix 2019 5
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#470 Point catalog reformat
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/photometry_tools.py
Labels: code cleanup, no-changelog-entry-needed

#472 Singletons 2019 5
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#475 New version of rmtree
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#478 More tweaks to try to remove directories
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#476 Add warning about minmed for N>5
  drizzlepac/processInput.py
Labels: feature request, no-changelog-entry-needed

#479 Force updatewcs in cases where exptime==0 for all inputs
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#480 Add segment columns
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/hla_flag_filter.py
Labels: code cleanup, no-changelog-entry-needed

#481 ABMAG calculation cleanup
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/comparison_tools/starmatch_hist.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/photometry_tools.py
Labels: code cleanup, no-changelog-entry-needed

#482 Streamline refactoring of hla_flag_filter.hla_nexp_flags()
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/hla_flag_filter.py
Labels: code cleanup, no-changelog-entry-needed

#486 Ignore bad data now and clip to output array shape
  drizzlepac/hlautils/cell_utils.py
Labels: bug, no-changelog-entry-needed

#487 Use PIL to generate masks
  drizzlepac/hlautils/cell_utils.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#484 Initial attempt to update poller file input formats
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/processing_utils.py
Labels: enhancement, no-changelog-entry-needed

#469 Simple change to report SVM in WCSNAME
  drizzlepac/hlautils/align_utils.py
  drizzlepac/updatehdr.py
Labels: bug, no-changelog-entry-needed

#483 Revise logging
  drizzlepac/align.py
  drizzlepac/alignimages.py
  drizzlepac/astrodrizzle.py
  drizzlepac/hapcatalog.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/ci_table.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/hlautils/se_source_generation.py
  drizzlepac/hlautils/sourcelist_generation.py
  drizzlepac/hlautils/testutils.py
  drizzlepac/runsinglehap.py
  drizzlepac/updatehdr.py
  drizzlepac/util.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#489 Reset num_cores to 1 for all astrodrizzle processes
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/any/any_astrodrizzle_filter_hap_basic.json
  drizzlepac/pars/hap_pars/default_parameters/any/any_astrodrizzle_n1.json
  drizzlepac/pars/hap_pars/default_parameters/any/any_astrodrizzle_single_hap_basic.json
  drizzlepac/pars/hap_pars/default_parameters/any/any_astrodrizzle_total_hap_basic.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_filter_hap_basic.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_n1.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_single_hap_basic.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_total_hap_basic.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
Labels: bug, no-changelog-entry-needed

#491 Fix problem with defining cells by ID
  drizzlepac/hlautils/cell_utils.py
Labels: bug, no-changelog-entry-needed

#492 Get log files written out correctly for multiple TDP
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/processing_utils.py
Labels: bug, no-changelog-entry-needed

#493 Protect logname removal
  drizzlepac/hapsequencer.py
Labels: enhancement, no-changelog-entry-needed

#494 Fixed typo
  drizzlepac/hlautils/hla_flag_filter.py
Labels: bug, no-changelog-entry-needed

#495 Expand logic to apply updatewcs if any exposures were originally skipped
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#497 Add converter to correctly interpret obset_id poller column
  drizzlepac/align.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/poller_utils.py
Labels: bug, no-changelog-entry-needed

#498 Finally cleaning up reference catalogs correctly
  drizzlepac/align.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#496 Update hla tests
  tests/hla/master_121.lst
  tests/hla/test_run_svmpoller.py
Labels: no-changelog-entry-needed, testing

#485 Update devutils flag display scripts to be compatible with reformatted point and segment catalogs
  drizzlepac/devutils/comparison_tools/compare_sourcelist_flagging.py
  drizzlepac/devutils/disp_sources_by_flag.py
Labels: bug, no-changelog-entry-needed

#505 Global rename of variable 'debug' to 'diagnostic_mode'
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/ci_table.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/runsinglehap.py
Labels: code cleanup, no-changelog-entry-needed

#508 Adjust where the reference catalogs are cleaned up
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#504 Format log messages to be DMS-compatible
  drizzlepac/align.py
  drizzlepac/alignimages.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/runsinglehap.py
Labels: code cleanup, no-changelog-entry-needed

#506 Add command-line input "log_level" to runsinglehap.py, hapsequencer.run_hap_processing
  drizzlepac/hapsequencer.py
  drizzlepac/runsinglehap.py
Labels: code cleanup, no-changelog-entry-needed

#523 Fix empty drz naming problem (HSTSDP-851)
  drizzlepac/processInput.py
Labels: bug, no-changelog-entry-needed

#510 Added user-defined log level functionality to hapsequencer.py, runsinglehap.py, ci_table.py, config_utils.py, and hla_flag_filter.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/ci_table.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/hlautils/hla_flag_filter.py
Labels: enhancement, no-changelog-entry-needed

#520 Add overlap diff verification to detect double-images
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed

#518 Added user-defined log level functionality to drizzlepac/hlautils/analyze.py, drizzlepac/hlautils/catalog_utils.py, drizzlepac/hlautils/poller_utils.py, and drizzlepac/hlautils/product.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/runsinglehap.py
Labels: enhancement, no-changelog-entry-needed
