Repository spacetelescope/drizzlepac, pull requests merged in 2019-07, with the labels that each got.

#418 Removed support for/mention of visit_id column
  drizzlepac/hlautils/pipeline_poller_utils.py
Labels: bug, no-changelog-entry-needed

#419 Update real product headers for CAOM compatibility
  drizzlepac/runhlaprocessing.py
Labels: bug, no-changelog-entry-needed

#421 Create manifest file
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/se_source_generation.py
  drizzlepac/hlautils/sourcelist_generation.py
  drizzlepac/runhlaprocessing.py
Labels: enhancement, no-changelog-entry-needed

#422 Get user-defined pytest config values through non-deprecated means.
  tests/resources.py
Labels: bug

#424 Update make_mosaic_wcs to produce a perfect CD matrix
  drizzlepac/wcs_functions.py
Labels: bug, no-changelog-entry-needed

#425 Implement sky cell support
  CHANGELOG.rst
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/pars/allsky_cells.fits
Labels: enhancement

#426 Add support for HSTWCS inputs to astrodrizzle
  CHANGELOG.rst
  drizzlepac/util.py
  drizzlepac/wcs_functions.py
Labels: enhancement
