Repository spacetelescope/drizzlepac, pull requests merged in 2019-02, with the labels that each got.

#213 Initial version which calls alignimages
  CHANGELOG.rst
  drizzlepac/runastrodriz.py
Labels: enhancement

#214 set 'update_hdr_wcs=True' in alignimages.perform_align() call in runastrodriz.py
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed

#216 Initial load of hlapipeline
  CHANGELOG.rst
  drizzlepac/__init__.py
  drizzlepac/alignimages.py
  drizzlepac/hlautils/__init__.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/bitmask.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/get_git_rev_info.py
  drizzlepac/hlautils/updatehdr.py
  drizzlepac/runastrodriz.py
Labels: enhancement

#217 Fix code, imports, and setup issues with HLA utils
  CHANGELOG.rst
  doc/.rtd-environment.yml
  doc/rtd-pip-requirements
  drizzlepac/alignimages.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/bitmask.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/get_git_rev_info.py
  drizzlepac/hlautils/updatehdr.py
  setup.py
Labels: bug, code cleanup

#218 Fix RTD yml
  .readthedocs.yml
Labels: Documentation, no-changelog-entry-needed

#219 Fix RTD env file
  doc/.rtd-environment.yml
Labels: Documentation, bug, no-changelog-entry-needed

#221 drizzlepac/alignimages.py: changed relative imports to absolute imports
  drizzlepac/alignimages.py
Labels: enhancement, no-changelog-entry-needed

#222 Astrometric catalog "GSC241" has been replaced with "GAIADR1" in alignimages.py.
  drizzlepac/alignimages.py
Labels: enhancement, no-changelog-entry-needed

#224 drizzlepac/alignimages.py: Simple bug fix. Fixed now incorrect pathnames in step 0 of perform_align().
  drizzlepac/alignimages.py
Labels: bug, no-changelog-entry-needed

#215 test with dependencies from the master branches
  JenkinsfileRT
Labels: no-changelog-entry-needed, testing

#225 Replace dependency on stsci.ndimage with scipy
  CHANGELOG.rst
  Jenkinsfile
  JenkinsfileRT
  doc/.rtd-environment.yml
  drizzlepac/findobj.py
  drizzlepac/tweakutils.py
  setup.py
Labels: code cleanup

#227 Remove dependency on stsci.imagemanip
  CHANGELOG.rst
  Jenkinsfile
  JenkinsfileRT
  doc/.rtd-environment.yml
  drizzlepac/stisData.py
  setup.py
Labels: bug, code cleanup

#228 Revise tests to better use tolerances
  tests/resources.py
Labels: no-changelog-entry-needed, testing

#230 Switch to Python 3 style super(); formating adjustments
  doc/source/conf.py
  drizzlepac/acsData.py
  drizzlepac/catalogs.py
  drizzlepac/imageObject.py
  drizzlepac/imgclasses.py
  drizzlepac/irData.py
  drizzlepac/mapreg.py
  drizzlepac/nicmosData.py
  drizzlepac/resetbits.py
  drizzlepac/staticMask.py
  drizzlepac/util.py
  drizzlepac/wcs_functions.py
  drizzlepac/wfc3Data.py
  drizzlepac/wfpc2Data.py
  setup_hooks.py
  tests/resources.py
Labels: code cleanup, no-changelog-entry-needed

#232 Try to fix some exceptions
  drizzlepac/alignimages.py
  drizzlepac/hlautils/astrometric_utils.py
Labels: bug, no-changelog-entry-needed

#233 Restore API for perform_align function
  drizzlepac/alignimages.py
  drizzlepac/runastrodriz.py
Labels: code cleanup, no-changelog-entry-needed

#235 Fixed STDOUT logging.
  CHANGELOG.rst
  drizzlepac/alignimages.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/get_git_rev_info.py
  drizzlepac/hlautils/updatehdr.py
Labels: enhancement

#234 Replacing #220 with de-conflicted changes, plus bug fixes to our code
  CHANGELOG.rst
  doc/.rtd-environment.yml
  drizzlepac/alignimages.py
  drizzlepac/hlautils/astrometric_utils.py
  setup.py
Labels: bug

#229 TST: Unpin pytest. Enable RT auto-notify on failure.
  Jenkinsfile
  JenkinsfileRT
Labels: no-changelog-entry-needed, testing

#236 Fix bug from #230
  drizzlepac/catalogs.py
Labels: bug, no-changelog-entry-needed

#241 Fix step7 logic
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: bug

#244 Debug align table
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: bug, code cleanup

#246 Bugfix: Correct perform_align() subroutine call in alignimages.py
  drizzlepac/alignimages.py
Labels: bug, no-changelog-entry-needed

#249 Add archive hdrlet
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: bug

#248 Astroquery import error
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: bug

#247 Configure stsci-bot to ignore milestone for this repository
  pyproject.toml
Labels: code cleanup, no-changelog-entry-needed

#250 Update runastrodriz to NOT overwrite hlet file
  CHANGELOG.rst
  drizzlepac/runastrodriz.py
Labels: bug
