Repository spacetelescope/drizzlepac, pull requests merged in 2019-09, with the labels that each got.

#442 Updates to include integration of configuration management and catalog utilities
  drizzlepac/alignimages.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/hlautils/photometry_tools.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_filter_hap_basic.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_n1.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_single_hap_basic.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_total_hap_basic.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_quality_control_all.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_quality_control_all.json
  drizzlepac/test_config_utils.py
  drizzlepac/wcs_functions.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#444 Necessary changes to setup.py for proper code and config file distrib…
  drizzlepac/hapsequencer.py
  setup.py
Labels: no-changelog-entry-needed

#445 updated ACS astrodrizzle json files
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
Labels: bug, no-changelog-entry-needed

#446 Added more logging to hapsequencer and removed "if debug"
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/product.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#448 Fix crash in update_from_shiftfile due to np.loadtxt
  CHANGELOG.rst
  drizzlepac/updatehdr.py
Labels: bug

#450 Add cmdline interface
  drizzlepac/hapsequencer.py
  drizzlepac/runsinglehap.py
  setup.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#451 Added trailer file to manifest
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#454 Fix rounding problem with creating meta_wcs
  drizzlepac/wcs_functions.py
Labels: bug, no-changelog-entry-needed

#453 CI Redux
  Jenkinsfile
  JenkinsfileRT
Labels: no-changelog-entry-needed

#455 Refactor background calc
  drizzlepac/devutils/make_hla_classic_region_file.py
  drizzlepac/hapcatalog.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/run_config_utils.py
  drizzlepac/test_config_utils.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#449 Add sourcelist comparison code
  drizzlepac/devutils/__init__.py
  drizzlepac/devutils/comparison_tools/__init__.py
  drizzlepac/devutils/comparison_tools/compare_images.py
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/comparison_tools/infrot.py
  drizzlepac/devutils/comparison_tools/run_regression_test.py
  drizzlepac/devutils/comparison_tools/starmatch_hist.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#456 Fix pyproject.toml exclusion from sdist
  MANIFEST.in
Labels: bug, no-changelog-entry-needed
