Repository spacetelescope/drizzlepac, pull requests merged in 2019-01, with the labels that each got.

#203 Fix step numbering in the index and other doc formatting issues
  CHANGELOG.rst
  doc/source/ablot.rst
  doc/source/adrizzle.rst
  doc/source/astrodrizzle.rsts
  doc/source/drizcr.rst
  doc/source/imageobject.rst
  doc/source/index.rst
  doc/source/median.rst
  doc/source/process.rst
  doc/source/sky.rst
  doc/source/static.rst
  doc/source/tweakreg.rst
  doc/source/tweakutils.rst
  doc/source/updatehdr.rst
  drizzlepac/ablot.help
  drizzlepac/adrizzle.help
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.help
  drizzlepac/astrodrizzle.py
  drizzlepac/buildmask.py
  drizzlepac/imgclasses.py
  drizzlepac/mapreg.help
  drizzlepac/photeq.py
  drizzlepac/pixtosky.help
  drizzlepac/pixtosky.py
  drizzlepac/sky.help
  drizzlepac/skytopix.help
  drizzlepac/staticMask.help
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.help
  drizzlepac/tweakreg.py
  drizzlepac/updatenpol.py
Labels: Documentation, no-changelog-entry-needed

#204 Correct miniconda dir in PATH definition
  JenkinsfileRT
Labels: no-changelog-entry-needed

#205 Revert to numpy.linalg for matrix inversion
  CHANGELOG.rst
  drizzlepac/linearfit.py
  drizzlepac/updatehdr.py
Labels: enhancement

#207 Remove py2 support. Use WCS.pixel_shape instead of naxis
  CHANGELOG.rst
  Jenkinsfile
  drizzlepac/__init__.py
  drizzlepac/ablot.py
  drizzlepac/acsData.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/buildmask.py
  drizzlepac/buildwcs.py
  drizzlepac/catalogs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/findobj.py
  drizzlepac/imageObject.py
  drizzlepac/imagefindpars.py
  drizzlepac/imgclasses.py
  drizzlepac/irData.py
  drizzlepac/linearfit.py
  drizzlepac/mapreg.py
  drizzlepac/mdriz.py
  drizzlepac/mdzhandler.py
  drizzlepac/minmed.py
  drizzlepac/nicmosData.py
  drizzlepac/outputimage.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/processInput.py
  drizzlepac/quickDeriv.py
  drizzlepac/refimagefindpars.py
  drizzlepac/resetbits.py
  drizzlepac/runastrodriz.py
  drizzlepac/sky.py
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/stisData.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/tweakutils.py
  drizzlepac/updatehdr.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
  drizzlepac/wcs_functions.py
  drizzlepac/wfc3Data.py
  drizzlepac/wfpc2Data.py
  setup.py
  src/arrdrizmodule.c
  tests/acs/test_unit.py
  tests/resources.py
Labels: code cleanup

#208 Logic updated in runastrodriz to call updatewcs separately
  drizzlepac/runastrodriz.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#212 Remove unnecessary PATH, HOME overrides
  JenkinsfileRT
Labels: bug, no-changelog-entry-needed
