Repository spacetelescope/drizzlepac, pull requests merged in 2019-04, with the labels that each got.

#283 Mods to add/update regression tests for alignment code
  CHANGELOG.rst
  drizzlepac/alignimages.py
  drizzlepac/hlautils/analyze.py
  tests/hla/base_classes.py
  tests/hla/base_test.py
  tests/hla/test_align.py
  tests/hla/test_randomlist.py
Labels: code cleanup, enhancement, in progress

#311 fix pep8
  drizzlepac/hlautils/astrometric_utils.py
Labels: code cleanup, no-changelog-entry-needed

#304 Always return filtered table
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: bug, no-changelog-entry-needed

#318 Remove catalog_utils; move functionality to test_randomlist
  drizzlepac/hlautils/catalog_utils.py
  tests/hla/test_randomlist.py
Labels: code cleanup, no-changelog-entry-needed

#308 alignimages.py print statement replacement
  drizzlepac/alignimages.py
Labels: code cleanup, no-changelog-entry-needed

#315 Updates made for regression tests based upon code review comments
  drizzlepac/hlautils/testutils.py
  tests/hla/process_randomlist.py
  tests/hla/test_align.py
  tests/hla/test_apriori.py
  tests/hla/test_randomlist.py
Labels: code cleanup, no-changelog-entry-needed, testing

#320 Bug fix in the automatic computation of the IVM weights
  CHANGELOG.rst
  drizzlepac/imageObject.py
Labels: bug

#312 fix docstrings in astrometric_utils
  doc/source/conf.py
  doc/source/hla.rst
  doc/source/index.rst
  drizzlepac/hlautils/astrometric_utils.py
Labels: Documentation, no-changelog-entry-needed

#307 Astroquery utils checkout
  drizzlepac/alignimages.py
  drizzlepac/hlautils/astroquery_utils.py
Labels: code cleanup, no-changelog-entry-needed

#317 Alignimages cleanup
  drizzlepac/alignimages.py
Labels: code cleanup, no-changelog-entry-needed

#321 Changed the nature of _random_select_from_csv() at this time.
  conftest.py
  tests/hla/process_randomlist.py
  tests/hla/test_randomlist.py
Labels: code cleanup, feature request, no-changelog-entry-needed, testing

#323 Pr314 completion
  doc/source/astrometry.rst
  doc/source/astrometry_api.rst
  doc/source/conf.py
  doc/source/index.rst
  drizzlepac/alignimages.py
  drizzlepac/hlautils/astrometric_utils.py
Labels: Documentation, code cleanup, no-changelog-entry-needed

#327 Display algorithm name at the end of alignimages run and in headerlet file (UPDATED)
  drizzlepac/alignimages.py
  drizzlepac/hlautils/analyze.py
Labels: feature request, no-changelog-entry-needed

#330 Bug fix - equality check versus same object
  drizzlepac/alignimages.py
Labels: bug, no-changelog-entry-needed

#333 Add alignimages.py git repo information to log file
  drizzlepac/hlautils/get_git_rev_info.py
Labels: code cleanup, no-changelog-entry-needed

#328 change processing order so that match_relative_fit is the preferred fit method
  drizzlepac/alignimages.py
Labels: feature request, no-changelog-entry-needed

#332 Hla 231 incorrect filtered table fields
  drizzlepac/alignimages.py
Labels: bug, no-changelog-entry-needed

#334 HLA 234: Add 'compromised' field in filtered_table by default
  drizzlepac/hlautils/analyze.py
Labels: bug, no-changelog-entry-needed

#335 DOC: Add RT link to README
  README.md
Labels: Documentation, no-changelog-entry-needed

#339 Repaired hla_staging branch manually
  conftest.py
  drizzlepac/alignimages.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/get_git_rev_info.py
  drizzlepac/hlautils/testutils.py
Labels: code cleanup, no-changelog-entry-needed

#340 Update to FWHM based on hla-staging branch instead
  drizzlepac/alignimages.py
Labels: bug, enhancement, no-changelog-entry-needed

#341 Parallelized testing
  conftest.py
  drizzlepac/alignimages.py
  setup.py
  tests/hla/ACSWFC3ListDefault50.csv
  tests/hla/process_randomlist.py
  tests/hla/test_randomlist.py
Labels: enhancement, feature request, no-changelog-entry-needed, testing

#343 Fix table pep8
  drizzlepac/alignimages.py
Labels: bug, no-changelog-entry-needed

#347 Fix segmentation problems from photutils
  drizzlepac/alignimages.py
  drizzlepac/hlautils/astrometric_utils.py
Labels: bug, no-changelog-entry-needed

#346 junit_xml is not a valid keyword
  setup.cfg
Labels: bug, no-changelog-entry-needed, testing

#348 Updated datasets for this test
  setup.cfg
  tests/hla/test_apriori.py
Labels: bug, no-changelog-entry-needed, testing

#351 Created script tests/combine_ecsv_files.py
  tests/combine_ecsv_files.py
Labels: feature request, no-changelog-entry-needed, testing

#344 Update docs
  doc/source/astrometry.rst
  doc/source/astrometry_api.rst
  doc/source/index.rst
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/testutils.py
Labels: Documentation, no-changelog-entry-needed

#353 Update setup
  setup.py
Labels: code cleanup, no-changelog-entry-needed, testing

#354 Fix apriori tests on master
  tests/hla/test_apriori.py
Labels: no-changelog-entry-needed, testing

#355 Disable hla apriori tests
  tests/hla/test_apriori.py
Labels: no-changelog-entry-needed, testing

#356 Disable WFPC2 waiver tests
  tests/wfpc2/test_wfpc2.py
Labels: no-changelog-entry-needed, testing
