Repository spacetelescope/drizzlepac, pull requests merged in 2019-12, with the labels that each got.

#519 Added code to vet the poller input images viability for drizzling
  drizzlepac/align.py
  drizzlepac/alignimages.py
  drizzlepac/hapcatalog.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/ci_table.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/hlautils/get_git_rev_info.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/hla_flag_filter_HLAClassic.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/hlautils/se_source_generation.py
  drizzlepac/hlautils/sourcelist_generation.py
  drizzlepac/hlautils/testutils.py
  drizzlepac/runsinglehap.py
Labels: Do Not Merge, bug, no-changelog-entry-needed

#528 Modify existing WFC3/IR configuration files for SVM processing
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
Labels: enhancement, no-changelog-entry-needed, parameter update

#530 Further protect variable refname in FilterProduct
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#529 Fixed filenames in ACS/SBC JSON index file
  drizzlepac/pars/hap_pars/acs_sbc_index.json
Labels: bug, no-changelog-entry-needed

#531 Added function to verify GAIA WCSNAMEs
  drizzlepac/devutils/alignment_viewer.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#512 Revise logging more
  drizzlepac/__init__.py
  drizzlepac/align.py
  drizzlepac/alignimages.py
  drizzlepac/devutils/disp_sources_by_flag.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/hlautils/testutils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/runastrodriz.py
  drizzlepac/runsinglehap.py
  tests/hla/test_align.py
  tests/hla/test_alignpipe_randomlist.py
  tests/hla/test_randomlist.py
Labels: bug, code cleanup, no-changelog-entry-needed

#536 skystat updated from "mode" to "median" in all astrodrizzle *any_total*.json files
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total_pre2012.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total_pre2012.json
Labels: no-changelog-entry-needed, parameter update

#538 Correct quick fix2019 5
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#540 Avoid zero exptime
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#541 Add automated HLA classic sourcelist comparison
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/comparison_tools/starmatch_hist.py
  drizzlepac/hapsequencer.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#547 Modified SkyFootprint build method
  drizzlepac/hlautils/cell_utils.py
Labels: bug, no-changelog-entry-needed
