Repository spacetelescope/drizzlepac, pull requests merged in 2019-03, with the labels that each got.

#251 Implement envvar control of alignment in runastrodriz
  CHANGELOG.rst
  drizzlepac/runastrodriz.py
Labels: enhancement

#254 Fix setuptools
  Jenkinsfile
  pyproject.toml
  setup.py
Labels: bug, no-changelog-entry-needed

#242 General cleanup and service integrations
  .coveragerc
  .gitignore
  Jenkinsfile
  README.md
  doc/.rtd-environment.yml
  setup.cfg
  setup.py
  setup_hooks.py
Labels: no-changelog-entry-needed

#260 Fixed interpret_fit_rms to handle relative alignments.
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: bug

#268 [WIP] fix relative alignment development
  CHANGELOG.rst
  drizzlepac/alignimages.py
  drizzlepac/hlautils/astrometric_utils.py
Labels: bug, enhancement

#271 Turned on new fit algorithm match_relative_fit
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: enhancement

#273 Fix VS compiler errors due to pointer arithmetic
  CHANGELOG.rst
  src/arrdrizmodule.c
Labels: bug

#253 Set up CI with Azure Pipelines
  .gitignore
  azure-pipelines.yml
  azure-templates.yml
  drizzlepac/processInput.py
  drizzlepac/updatenpol.py
  setup.py
  tests/resources.py
Labels: code cleanup, no-changelog-entry-needed

#275 Implement PEP8 check
  azure-pipelines.yml
  setup.cfg
Labels: no-changelog-entry-needed, testing

#276 Add azure badge
  README.md
Labels: no-changelog-entry-needed

#281 Hla 210 support hla naming convention
  drizzlepac/generate_final_product_filenames.py
Labels: in progress, no-changelog-entry-needed

#285 Implement ci_watson
  Jenkinsfile
  azure-pipelines.yml
  azure-templates.yml
  conftest.py
  setup.cfg
  setup.py
  tests/acs/test_acs_kernels.py
  tests/acs/test_acs_narrowband.py
  tests/acs/test_asn_regress.py
  tests/helpers/__init__.py
  tests/helpers/io.py
  tests/helpers/mark.py
  tests/helpers/utils.py
  tests/resources.py
  tests/wfc3/test_vary_perf.py
  tests/wfc3/test_wfc3.py
  tests/wfpc2/test_wfpc2.py
Labels: no-changelog-entry-needed

#287 JenkinsfileRT: Add ci-watson
  JenkinsfileRT
Labels: no-changelog-entry-needed

#289 Fix failing WFPC2 tests
  tests/resources.py
  tests/wfpc2/test_wfpc2.py
Labels: bug, no-changelog-entry-needed

#286 Improve 2D-histogram intitial shift estimation algorithm
  CHANGELOG.rst
  drizzlepac/imgclasses.py
  drizzlepac/tweakutils.py
Labels: bug, code cleanup

#294 Add astrometry tests
  CHANGELOG.rst
  drizzlepac/alignimages.py
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/testutils.py
  tests/hla/__init__.py
  tests/hla/test_apriori.py
Labels: enhancement, testing

#299 Fix envvar bug, and added force parameter
  drizzlepac/hlautils/testutils.py
Labels: bug, no-changelog-entry-needed, testing

#259 Ensure singletons do not use the match_relative_fit algorithm
  CHANGELOG.rst
  drizzlepac/alignimages.py
Labels: Do Not Merge, bug

#298 Streamline command-line interface section of alignimages.py
  drizzlepac/alignimages.py
Labels: code cleanup, enhancement, no-changelog-entry-needed
