Repository spacetelescope/drizzlepac, pull requests merged in 2019-08, with the labels that each got.

#427 OO refactor source code
  CHANGELOG.rst
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/pipeline_poller_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/runhlaprocessing.py
Labels: code cleanup

#429 Correct singleton CTE processing in runastrodriz
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/runastrodriz.py
  requirements-dev.txt
  setup.py
  tests/hla/test_pipeline.py
Labels: bug, no-changelog-entry-needed, testing

#430 Support user-defined WCSNAME values
  drizzlepac/updatehdr.py
  tests/hla/test_apriori.py
Labels: bug, no-changelog-entry-needed

#428 [WIP] Parameter configuration module
  drizzlepac/config_testbed.py
  drizzlepac/hlautils/config_utils.py
  drizzlepac/make_cfgobj_files.py
  drizzlepac/pars/config_testbed.cfg
  drizzlepac/pars/config_testbed.cfgspc
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/acs_hrc_index.json
  drizzlepac/pars/hap_pars/acs_sbc_index.json
  drizzlepac/pars/hap_pars/acs_wfc_index.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_filter_hap_basic.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_n1.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_single_hap_basic.json
  drizzlepac/pars/hap_pars/any/any_astrodrizzle_total_hap_basic.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
  drizzlepac/pars/hap_pars/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
  drizzlepac/pars/hap_pars/wfc3_ir_index.json
  drizzlepac/pars/hap_pars/wfc3_uvis_index.json
  drizzlepac/pars/runhap.config
  drizzlepac/pars/runhlaprocessing_config.spec
  drizzlepac/test_config_utils.py
Labels: code cleanup, enhancement, in progress, no-changelog-entry-needed

#432 Rename module to not be a test
  drizzlepac/run_config_utils.py
Labels: code cleanup, no-changelog-entry-needed, testing

#431 update test and install deps
  azure-templates.yml
  requirements-dev.txt
  setup.py
Labels: no-changelog-entry-needed

#433 Fix logic for interpreting wcsname
  drizzlepac/updatehdr.py
Labels: bug, no-changelog-entry-needed

#435 Updating astroquery build reqs for testing
  JenkinsfileRT
  requirements-dev.txt
Labels: code cleanup, no-changelog-entry-needed, testing

#420 Sourcelist code object-oriented refactor
  drizzlepac/hapcatalog.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/photometry_tools.py
  drizzlepac/hlautils/run_sourcelist_generation.py
  drizzlepac/test_config_utils.py
Labels: code cleanup, no-changelog-entry-needed

#439 add config object instantiation
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/product.py
Labels: enhancement, in progress, no-changelog-entry-needed

#415 Ignore Emacs temp file
  .gitignore
Labels: code cleanup, no-changelog-entry-needed

#443 Correct logic in runastrodriz for CTE singletons
  drizzlepac/runastrodriz.py
  tests/hla/test_pipeline.py
Labels: bug, no-changelog-entry-needed
