Repository spacetelescope/drizzlepac, pull requests merged in 2019-06, with the labels that each got.

#389 [WIP] Continued development of new HLA processing interface
  drizzlepac/hlautils/background_median.py
  drizzlepac/hlautils/ci_ap_cor_table_ap_20_2016.txt
  drizzlepac/hlautils/ci_table.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/hla_toolbox.py
  drizzlepac/hlautils/photometry_tools.py
  drizzlepac/hlautils/run_sourcelist_generation.py
  drizzlepac/hlautils/sourcelist_generation.py
  drizzlepac/runhlaprocessing.py
  drizzlepac/wcs_functions.py
  setup.py
Labels: enhancement, in progress, no-changelog-entry-needed

#391 Pipeline poller interpreter utility routines
  drizzlepac/generate_final_product_filenames.py
  drizzlepac/hlautils/pipeline_poller_utils.py
  setup.py
Labels: feature request, no-changelog-entry-needed

#390 Update headers to meet CAOM/Archive reqs
  drizzlepac/alignimages.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/pars/acs_header_hla.rules
  drizzlepac/pars/wfc3_header_hla.rules
  drizzlepac/updatehdr.py
Labels: bug, no-changelog-entry-needed

#396 Include wsctype in drz product headers
  drizzlepac/outputimage.py
  drizzlepac/updatehdr.py
Labels: bug, no-changelog-entry-needed

#397 Fix bug: Interpret poller from pipeline
  drizzlepac/hlautils/pipeline_poller_utils.py
Labels: bug, no-changelog-entry-needed

#394 [WIP] Generation of SExtractor-like source generation catalogs
  drizzlepac/hlautils/se_source_generation.py
Labels: enhancement, no-changelog-entry-needed

#393 [WIP] DAO-like sourcelist generation code refactoring
  drizzlepac/hlautils/run_sourcelist_generation.py
  drizzlepac/hlautils/sourcelist_generation.py
  drizzlepac/runhlaprocessing.py
Labels: enhancement, no-changelog-entry-needed

#399 Revise HAPEXPNAME for level 2 products
  drizzlepac/hlautils/processing_utils.py
Labels: bug, no-changelog-entry-needed

#401 Remove APERTURE as a discriminant and limit FILTER to eliminate only …
  drizzlepac/hlautils/analyze.py
Labels: bug, no-changelog-entry-needed

#400 Updates to the SExtractor-like catalog generation code.
  drizzlepac/hlautils/se_source_generation.py
Labels: enhancement, no-changelog-entry-needed

#403 Add PA_V3 to ACS HAP rules to insure consistency for HAP products
  drizzlepac/pars/acs_header_hla.rules
Labels: bug, no-changelog-entry-needed

#404 Move keywords in HAP products to be consistent
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/pars/acs_header_hla.rules
Labels: bug, no-changelog-entry-needed

#405 Fix segm parameters
  drizzlepac/hlautils/se_source_generation.py
Labels: bug, no-changelog-entry-needed

#406 Enforce pixtopix verbose setting when not run as a script
  CHANGELOG.rst
  drizzlepac/pixtopix.help
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.help
  drizzlepac/util.py
Labels: bug, code cleanup

#407 Refactoring of run_astrodrizzle subroutine, addition of segmap sourcelist generation to runhlaprocessing.py
  drizzlepac/alignimages.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/run_sourcelist_generation.py
  drizzlepac/hlautils/se_source_generation.py
  drizzlepac/hlautils/sourcelist_generation.py
  drizzlepac/pars/acs_header_hla.rules
  drizzlepac/pars/astrodrizzle_filter_hap.cfg
  drizzlepac/pars/astrodrizzle_single_hap.cfg
  drizzlepac/pars/astrodrizzle_total_hap.cfg
  drizzlepac/runhlaprocessing.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#410 Adding cmd line interface to runhlaprocessing
  setup.py
Labels: enhancement, no-changelog-entry-needed

#411 Add main for runhap to call
  drizzlepac/runhlaprocessing.py
Labels: bug, no-changelog-entry-needed

#413 Return status value
  drizzlepac/runhlaprocessing.py
Labels: enhancement, no-changelog-entry-needed

#414 DOC: Update year on license
  LICENSE.txt
Labels: Documentation, no-changelog-entry-needed
