Repository spacetelescope/drizzlepac, pull requests merged in 2020-06, with the labels that each got.

#674 Add new parameter for pipeline use of custom rules files
  CHANGELOG.rst
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.help
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/processing_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/outputimage.py
  drizzlepac/pars/acs_header_hap.rules
  drizzlepac/pars/astrodrizzle.cfg
  drizzlepac/pars/astrodrizzle.cfgspc
  drizzlepac/pars/wfc3_header_hap.rules
Labels: bug

#477 New PC size of 4.2, SC size of about 0.2
  drizzlepac/pars/allsky_cells.fits
Labels: feature request, no-changelog-entry-needed

#678 update diagnostic_utils.py to accept new inputs
  drizzlepac/hlautils/diagnostic_utils.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#676 Update poller_utils to interpret MVM poller files
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/product.py
  setup.py
Labels: enhancement, no-changelog-entry-needed

#675 Rename hlautils directory to haputils
  doc/source/astrometry.rst
  doc/source/astrometry_api.rst
  doc/source/hla.rst
  drizzlepac/__init__.py
  drizzlepac/align.py
  drizzlepac/devutils/alignment_viewer.py
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/comparison_tools/integrate_read_hla_catalog.py
  drizzlepac/devutils/plot_ci_vs_fwhm.py
  drizzlepac/devutils/test_hla_flag_filter.py
  drizzlepac/devutils/validate_hla_flag_filter.py
  drizzlepac/hapcatalog.py
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/__init__.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/astroquery_utils.py
  drizzlepac/haputils/background_median.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/ci_table.py
  drizzlepac/haputils/config_utils.py
  drizzlepac/haputils/diagnostic_json_harvester.py
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/get_git_rev_info.py
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/haputils/hla_flag_filter_HLAClassic.py
  drizzlepac/haputils/photometry_graphics.py
  drizzlepac/haputils/photometry_tools.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/processing_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/haputils/qa_harvest.py
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/run_sourcelist_generation.py
  drizzlepac/haputils/se_source_generation.py
  drizzlepac/haputils/sourcelist_generation.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/haputils/testutils.py
  drizzlepac/run_config_utils.py
  drizzlepac/run_hla_flag_filter.py
  drizzlepac/runastrodriz.py
  tests/hap/ACSWFC3ListDefault50.csv
  tests/hap/__init__.py
  tests/hap/base_classes.py
  tests/hap/base_test.py
  tests/hap/master_121.lst
  tests/hap/test_align.py
  tests/hap/test_alignpipe_randomlist.py
  tests/hap/test_apriori.py
  tests/hap/test_pipeline.py
  tests/hap/test_randomlist.py
  tests/hap/test_run_svmpoller.py
  tests/hla/__init__.py
Labels: code cleanup, no-changelog-entry-needed

#681 Updated SVM Quality Analysis tests
  drizzlepac/haputils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#679 Insure rscale as primary/default fit mode for all alignment
  drizzlepac/haputils/align_utils.py
Labels: enhancement, no-changelog-entry-needed

#680 Update relative astrometric resids to use HapDiagnostics
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#682 update json harvester code to process 'units' and 'descriptions' information from json files, write dataframe and metadata to HDF5 file
  doc/.rtd-environment.yml
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/haputils/diagnostic_json_harvester.py
  drizzlepac/haputils/svm_quality_analysis.py
  setup.py
Labels: enhancement, no-changelog-entry-needed

#683 Comment out Windows builds for now
  azure-pipelines.yml
Labels: no-changelog-entry-needed, testing

#685 Generate a Bokeh graphic which can be used as an example for other plotting routines
  drizzlepac/haputils/diagnostic_json_harvester.py
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/photometry_graphics.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: code cleanup, feature request, no-changelog-entry-needed

#686 Update all alignment parameter files to force use of rscale only
  drizzlepac/align.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed

#687 Remove override of TEST_BIGDATA definition
  tests/hap/test_pipeline.py
Labels: no-changelog-entry-needed, testing

#688 Add HAPLEVEL to ExposureProduct file headers
  drizzlepac/haputils/product.py
Labels: bug, no-changelog-entry-needed

#684 Use Bokeh for relative alignment scalar plots
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/pars/acs_header_hap.rules
  setup.py
Labels: enhancement, no-changelog-entry-needed

#689 Updated report_wcs() in svm_quality_analysis.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#693 Fix cal QA errors found during testing
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/quality_analysis.py
Labels: bug, no-changelog-entry-needed

#692 Update QA plots with useful Bokeh tools
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#696 Add taskname to quality_analysis
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/quality_analysis.py
Labels: bug, no-changelog-entry-needed

#694 Update photometry graphics
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/photometry_graphics.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#691 Expand search for JSON files in harvester
  drizzlepac/haputils/diagnostic_json_harvester.py
Labels: enhancement, no-changelog-entry-needed

#695 Generated standalone version of wcs_graphics.py
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/wcs_graphics.py
Labels: feature request, no-changelog-entry-needed

#698 SVM Q&A: Create graphics routine for "find_gaia_sources"
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/n_gaia_sources_graphics.py
Labels: enhancement, no-changelog-entry-needed
