Repository spacetelescope/drizzlepac, pull requests merged in 2020-02, with the labels that each got.

#579 Fix bug introduced in commit fc98ce6 for diagnostic mode only.
  drizzlepac/hlautils/catalog_utils.py
Labels: bug, no-changelog-entry-needed

#581 Keep HDRNAME consistent with WCSNAME
  drizzlepac/hlautils/align_utils.py
Labels: bug, no-changelog-entry-needed

#580 Add hdrname to hdulist
  doc/source/index.rst
  doc/source/pixreplace.rst
  drizzlepac/__init__.py
  drizzlepac/hlautils/align_utils.py
Labels: Documentation, bug, no-changelog-entry-needed

#583 proposed bug fix for 2dhist int bin number requirement
  drizzlepac/imgclasses.py
Labels: bug, no-changelog-entry-needed

#585 Check the input file to make sure it does not have zero size.
  drizzlepac/hlautils/poller_utils.py
Labels: enhancement, no-changelog-entry-needed

#587 Fix crash due to float number of bins passed to histogram2d
  CHANGELOG.rst
  drizzlepac/imgclasses.py
Labels: bug, enhancement

#586 Modified the handling of the filter values to accommodate SBC names
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/poller_utils.py
Labels: bug, no-changelog-entry-needed

#589 Do not look for CCDGAIN keyword in SBC FITS headers.
  drizzlepac/hlautils/catalog_utils.py
Labels: bug, no-changelog-entry-needed

#594 HSTDP 2019.5.2 quick-fix
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#592 Segmented Catalog Updates
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/product.py
Labels: bug, enhancement, no-changelog-entry-needed

#597 Modify SVM code to handle "no sources found" gracefully
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
Labels: bug, no-changelog-entry-needed

#598 Fix background subtraction
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/photometry_tools.py
Labels: bug, no-changelog-entry-needed

#593 Fix HSTDP 2019.5.1 bugs
  CHANGELOG.rst
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/imgclasses.py
  drizzlepac/runastrodriz.py
Labels: Do Not Merge, bug, in progress, no-changelog-entry-needed

#596 Minimum changes in pipeline code needed to use new tweakwcs
  CHANGELOG.rst
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  setup.py
Labels: bug, enhancement

#599 Make hla_flag_filter.py concentration index limits user-definable
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_quality_control_all.json
Labels: bug, no-changelog-entry-needed, parameter update

#601 Remove duplicate function; refer to correct fit_info values
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
Labels: bug, code cleanup, no-changelog-entry-needed
