Repository spacetelescope/drizzlepac, pull requests merged in 2020-05, with the labels that each got.

#648 Added an additional test to svm_quality_analysis.py.
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/svm_quality_analysis.py
  drizzlepac/wcs_functions.py
Labels: bug, code cleanup, enhancement, no-changelog-entry-needed

#655 Resolve HSTDP2020.2 WCS exceptions
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#657 Resolve HSTDP2020.2 WCS exceptions (#655)
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#658 Move rc2 to 318x
  drizzlepac/align.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/hlautils/hla_flag_filter.py
  drizzlepac/hlautils/quality_analysis.py
Labels: code cleanup, no-changelog-entry-needed

#656 add general info section to json files, standardize 'generation date/time' and 'time since epoch' values across all json files
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/diagnostic_json_harvester.py
  drizzlepac/hlautils/diagnostic_utils.py
  drizzlepac/hlautils/qa_harvest.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#661 Prototype Bokeh graphic to support SVM quality assessment data
  drizzlepac/hlautils/photometry_graphics.py
Labels: enhancement, feature request, no-changelog-entry-needed

#660 Move subroutine hapsequencer.run_sourcelist_comparision() to svm_quality_analysis.py.
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#662 compare_sourcelists.py : Store statistical summaries computed for each comparison to the .json file
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
Labels: enhancement, no-changelog-entry-needed

#663 Improve catalog memory
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
Labels: code cleanup, enhancement, no-changelog-entry-needed

#664 Initial fix for manifest file
  drizzlepac/hapcatalog.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/make_cfgobj_files.py
  drizzlepac/run_config_utils.py
Labels: bug, no-changelog-entry-needed

#665 Update imports of interpret_big_flags to use astropy instead
  drizzlepac/imgclasses.py
  drizzlepac/processInput.py
  drizzlepac/resetbits.py
  drizzlepac/sky.py
Labels: enhancement, no-changelog-entry-needed

#668 Updates to SVM Quality Test "report wcs".
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: bug, no-changelog-entry-needed

#670 Fix a crash when finding sources in very large images
  CHANGELOG.rst
  drizzlepac/findobj.py
Labels: bug

#667 Add json harvester script
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/hlautils/diagnostic_json_harvester.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: bug, enhancement, no-changelog-entry-needed

#669 Address problems from testing svm0.2.5
  CHANGELOG.rst
  drizzlepac/align.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/hlautils/testutils.py
  drizzlepac/runastrodriz.py
  setup.py
  tests/acs/test_acs_tweak.py
Labels: bug, in progress, no-changelog-entry-needed

#672 Fix critical bugs in svm026
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/poller_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed
