Repository spacetelescope/drizzlepac, pull requests merged in 2020-04, with the labels that each got.

#623 Segmentation catalog bug in diagnostic mode
  drizzlepac/hlautils/catalog_utils.py
Labels: bug, no-changelog-entry-needed

#624 Basic structure to support the invocation of the SVM quality assurance analysis
  drizzlepac/hapsequencer.py
  setup.py
Labels: feature request, no-changelog-entry-needed

#611 Creation of diagnostic_utils.py, retrofit of selected diagnostic routines
  drizzlepac/devutils/comparison_tools/compare_sourcelist_flagging.py
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/comparison_tools/integrate_read_hla_catalog.py
  drizzlepac/devutils/plot_ci_vs_fwhm.py
  drizzlepac/devutils/test_hla_flag_filter.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/diagnostic_utils.py
  drizzlepac/hlautils/poller_utils.py
Labels: enhancement, no-changelog-entry-needed

#625 Initial module to evaluate the SVM data products
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: feature request, no-changelog-entry-needed

#626 Report the number and disposition of GAIA sources which overlap the footprint of the SVM image product.
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#627 Add Zenodo DOI badge
  README.md
Labels: Documentation

#628 Add PyYAML to the setup.py which is needed for HAP SVM processing.
  setup.py
Labels: feature request, no-changelog-entry-needed

#632 Reset initialization for pipeline QA test
  drizzlepac/hlautils/quality_analysis.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#633 Added the compare_photometry() routine to the svm_quality_analysis.py module.
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: feature request, no-changelog-entry-needed

#629 Compare RA/Dec of cross-matches sources in Point and Segment Catalogs
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/diagnostic_utils.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#635 Enable control over fitgeom in alignment
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/hlautils/quality_analysis.py
Labels: bug, enhancement, no-changelog-entry-needed

#637 Rework within_footprint to work
  drizzlepac/hlautils/astrometric_utils.py
Labels: bug, code cleanup, no-changelog-entry-needed

#638 Ensure return variable is initialized.
  drizzlepac/hlautils/get_git_rev_info.py
Labels: bug, no-changelog-entry-needed

#641 Fix "SVM coordinate comparison can fail" bug
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: bug, no-changelog-entry-needed

#636 Add SVM Q+A function to statistically characterize the distribution of GAIA sources identified within a given HAP final product image footprint
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: bug, code cleanup, enhancement, no-changelog-entry-needed

#643 Improve memory usage in alignment for SVM processing
  drizzlepac/align.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/hlautils/hla_flag_filter.py
Labels: Do Not Merge, code cleanup, enhancement, in progress, no-changelog-entry-needed

#650 Fix an error condition for QA code
  drizzlepac/hlautils/quality_analysis.py
Labels: bug, no-changelog-entry-needed

#651 Add error logic for pipeline QA code
  drizzlepac/hlautils/quality_analysis.py
Labels: bug, no-changelog-entry-needed

#646 Add call to execute svm_quality_analysis.characterize_gaia_distribution() in hapsequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/diagnostic_json_harvester.py
  drizzlepac/hlautils/svm_quality_analysis.py
Labels: bug, code cleanup, feature request, no-changelog-entry-needed

#652 Correct debug statement in AlignmentTable
  drizzlepac/hlautils/align_utils.py
Labels: bug, no-changelog-entry-needed

#654 Address error case in AlignmentTable
  drizzlepac/hlautils/align_utils.py
Labels: bug, no-changelog-entry-needed
