Repository spacetelescope/drizzlepac, pull requests merged in 2020-08, with the labels that each got.

#760 Wrote documentation for aperture catalog generation
  doc/source/catalog_generation.rst
  doc/source/index.rst
  doc/source/singlevisit.rst
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/photometry_tools.py
Labels: Documentation, no-changelog-entry-needed

#759 Updated svm_quality_analysis module to generate additional data
  drizzlepac/haputils/svm_quality_analysis.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#761 Create "Delta_Mag vs Mag" and "Separation vs Mag" graphics
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/svm_quality_graphics.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#762 PIPELINE and SVM Q&A: Capture exceptions generated by the PIPELINE and SVM quality analysis routines
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#763 PIPELINE and SVM Q&A: Capture exceptions generated by the PIPELINE and SVM quality graphics routines
  drizzlepac/haputils/pipeline_graphics.py
  drizzlepac/haputils/svm_quality_graphics.py
Labels: enhancement, no-changelog-entry-needed

#764 Added proper argparse-controlled fault-tolerant command-line interface to svm_quality_graphics.py
  drizzlepac/haputils/svm_quality_graphics.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#765 svm_quality_graphics.py code updates and bugfixes
  drizzlepac/haputils/svm_quality_graphics.py
Labels: bug, enhancement, jirahub-ignore, no-changelog-entry-needed

#771 Fix logic for SVM with multiple detectors and possiblity of detection of no sources
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed

#772 Handle empty images in alignment
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#773 Improved JSON data collection for "number of sources" statistics
  drizzlepac/haputils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#768 SVM Q&A: Develop command-line interface for pipeline graphics
  drizzlepac/haputils/pipeline_graphics.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#776 Define a shared location on disk for HLA comparison output files
  drizzlepac/devutils/pars_utils.py
  drizzlepac/devutils/sourcelist_generation.py
  drizzlepac/haputils/comparison_utils.py
  drizzlepac/haputils/infrot.py
  drizzlepac/haputils/omegaxyz.py
  drizzlepac/haputils/read_hla_catalog.py
  drizzlepac/haputils/run_sourcelist_generation.py
  drizzlepac/haputils/starmatch_hist.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/haputils/svm_quality_graphics.py
  drizzlepac/run_hla_flag_filter.py
Labels: code cleanup, jirahub-ignore, no-changelog-entry-needed

#780 MNT: Remove nose and move scikit-image dependencies
  setup.py
Labels: no-changelog-entry-needed

#784 Update all WCSs with correct WCSTYPE keyword value
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed
