Repository spacetelescope/drizzlepac, pull requests merged in 2020-12, with the labels that each got.

#873 Revise MVM manifest name to be more generic
  drizzlepac/haputils/product.py
Labels: bug, in progress, jirahub-ignore, no-changelog-entry-needed, ready

#874 Manage MVM input data
  drizzlepac/haputils/poller_utils.py
Labels: enhancement, no-changelog-entry-needed

#876 Rename static mask
  CHANGELOG.rst
  drizzlepac/acsData.py
  drizzlepac/imageObject.py
  drizzlepac/nicmosData.py
  drizzlepac/processInput.py
  drizzlepac/stisData.py
  drizzlepac/wfc3Data.py
  drizzlepac/wfpc2Data.py
Labels: bug, jirahub-ignore, ready

#877 Rename static mask (#876)
  CHANGELOG.rst
  drizzlepac/acsData.py
  drizzlepac/imageObject.py
  drizzlepac/nicmosData.py
  drizzlepac/processInput.py
  drizzlepac/stisData.py
  drizzlepac/wfc3Data.py
  drizzlepac/wfpc2Data.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#875 Add renamed input files to MVM manifest file
  drizzlepac/hapmultisequencer.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed, ready

#888 Create more specific static mask name
  drizzlepac/imageObject.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#889 Create more specific static mask name (#888)
  drizzlepac/imageObject.py
Labels: code cleanup, jirahub-ignore, no-changelog-entry-needed

#878 Revise SkyCell API
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
Labels: code cleanup, in progress, jirahub-ignore, no-changelog-entry-needed

#898 Fixed two bugs during SVM testing: attribute not part of a class and error in joining tables
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed

#896 User can't specify a custom parameter file for SVM processing when executing from the command line
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/generate_custom_svm_param_file.py
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_filter_hap_basic.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_n1.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_single_hap_basic.json
  drizzlepac/pars/hap_pars/user_parameters/any/any_astrodrizzle_total_hap_basic.json
  drizzlepac/pars/hap_pars/user_parameters/any/ci_ap_cor_table_ap_20_2016.txt
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_total_pre2012.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_quality_control_all.json
  drizzlepac/runsinglehap.py
Labels: code cleanup, enhancement, no-changelog-entry-needed, parameter update

#895 Fix segment background determination and use
  drizzlepac/devutils/alignment_viewer.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: bug, jirahub-ignore, no-changelog-entry-needed, ready

#904 Fix arithmetic in the docstring for dqbits
  drizzlepac/astrodrizzle.help
  drizzlepac/imagefindpars.help
  drizzlepac/refimagefindpars.help
Labels: Documentation
