Repository spacetelescope/drizzlepac, pull requests merged in 2020-10, with the labels that each got.

#822 MVM: Set parameters based on input files
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/config_utils.py
Labels: enhancement, no-changelog-entry-needed

#827 Re-organize/streamline background computation algorithms
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: code cleanup, no-changelog-entry-needed

#828 Fix a bug introduced when cleaning up two-dimensional images
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: Do Not Merge, bug

#815 Get single-image CR algorithm working
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/graph_utils.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_astrodrizzle_blue_n6.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_astrodrizzle_grism_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_n6.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n2.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n4.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_astrodrizzle_any_pre2012_n6.json
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#829 Try another fit to GAIA if necessary
  drizzlepac/haputils/product.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#835 Scale parameters relative to HLA plate scale
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_quality_control_all.json
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#834 Set the gain to a value of 1.0 when processing ACS/SBC data
  drizzlepac/haputils/catalog_utils.py
Labels: bug

#836 Write the Segment "regions" file (*.reg) for use with ds9 after the catalog sources have been trimmed
  drizzlepac/haputils/catalog_utils.py
Labels: enhancement, no-changelog-entry-needed

#832 Refine auto kernel
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: Do Not Merge, enhancement, in progress, jirahub-ignore, no-changelog-entry-needed

#837 Add computation for the minimum allowable threshold
  drizzlepac/haputils/catalog_utils.py
Labels: bug, enhancement

#839 Implement catalog rejection based on expected CR levels
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_quality_control_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#840 Insure default value for n1 exptime
  drizzlepac/hapsequencer.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#844 Removed debug code from catalog_utils
  drizzlepac/haputils/catalog_utils.py
Labels: bug, code cleanup, jirahub-ignore, no-changelog-entry-needed, ready

#845 Implement env variables for catalog generation
  azure-templates.yml
  drizzlepac/hapsequencer.py
  setup.py
Labels: enhancement, no-changelog-entry-needed, ready

#847 Fix saturation mask application to input files
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
Labels: Documentation, bug, jirahub-ignore, no-changelog-entry-needed, ready

#850 Fix problem defining masks for use in point catalog generation
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed, ready

#849 Add interdetector crossmatch statistics utility "interdetector_sourcelist_crossmatch.py" to comparison_utils
  drizzlepac/devutils/comparison_tools/interdetector_sourcelist_crossmatch.py
Labels: no-changelog-entry-needed, testing

#846 Address identically zero background seen in SBC images
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: code cleanup, no-changelog-entry-needed
