Repository spacetelescope/drizzlepac, pull requests merged in 2020-03, with the labels that each got.

#604 Fix a bug in how minobj is used
  CHANGELOG.rst
  drizzlepac/imgclasses.py
Labels: bug

#605 Correct overly complex verification logic
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#606 Write out alignment's selected fit in debug mode
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed

#608 Refine overlap diff for blank images
  drizzlepac/hlautils/astrometric_utils.py
Labels: enhancement, no-changelog-entry-needed

#609 Insure blank images are actually blank
  drizzlepac/hlautils/astrometric_utils.py
Labels: enhancement, no-changelog-entry-needed

#607 Add astrometric residual computation as JSON file
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/quality_analysis.py
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed, testing

#612 Bug fix for overlap computation on blank fields
  drizzlepac/hlautils/astrometric_utils.py
Labels: bug, no-changelog-entry-needed

#614 Apply CR flagging every time WCS fails verification
  azure-templates.yml
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, code cleanup, enhancement, no-changelog-entry-needed

#613 Map stored token value on to a var that codecov honors.
  JenkinsfileRT
Labels: no-changelog-entry-needed, testing

#615 Remove codecov --token flag; rely upon env var instead.
  JenkinsfileRT
Labels: no-changelog-entry-needed, testing

#617 Merge old similarity with overlap diff
  drizzlepac/hlautils/astrometric_utils.py
Labels: enhancement, no-changelog-entry-needed

#616 Fix various bugs
  drizzlepac/align.py
  drizzlepac/devutils/alignment_viewer.py
  drizzlepac/hlautils/quality_analysis.py
  drizzlepac/runastrodriz.py
Labels: bug, enhancement, no-changelog-entry-needed

#610 Add docstring to alignment viewer code
  drizzlepac/devutils/alignment_viewer.py
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/hlautils/quality_analysis.py
Labels: Documentation, enhancement, no-changelog-entry-needed

#619 Insure background subtraction is consistently applied
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astroquery_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#602 Diagnostic updates and other miscellaneous code tweaks
  drizzlepac/devutils/comparison_tools/compare_sourcelist_flagging.py
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/plot_ci_vs_fwhm.py
  drizzlepac/devutils/validate_hla_flag_filter.py
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: bug, code cleanup, enhancement, no-changelog-entry-needed, parameter update

#620 Fix bugs in alignment_viewer
  drizzlepac/devutils/alignment_viewer.py
Labels: bug, enhancement, no-changelog-entry-needed, testing

#621 Fix fitmask exceptions for blank images
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/quality_analysis.py
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#622 Insure src catalog always has same number of columns
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed
