Repository spacetelescope/drizzlepac, pull requests merged in 2020-07, with the labels that each got.

#706 Use min obj as define in default parameter config files
  drizzlepac/haputils/align_utils.py
Labels: bug, no-changelog-entry-needed

#708 Only determine astrometric residuals for aposteriori WCSs
  drizzlepac/haputils/quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#709 Add CPDIS and DP to the list of distortion keywords
  CHANGELOG.rst
  drizzlepac/outputimage.py
Labels: bug

#711 Add pipeline Q&A vector plots
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/quality_analysis.py
Labels: bug, code cleanup, enhancement, no-changelog-entry-needed

#712 Fix WCSUTIL import from #710
  drizzlepac/adrizzle.py
Labels: bug, no-changelog-entry-needed

#671 Update docs to describe astrometry processing more fully
  doc/source/astrometry.rst
  doc/source/hla.rst
  doc/source/index.rst
  doc/source/runastrodriz.rst
Labels: Documentation, no-changelog-entry-needed

#713 Fix clumsy text in runastrodriz docs
  doc/source/runastrodriz.rst
Labels: Documentation, jirahub-ignore, no-changelog-entry-needed

#714 Update adrizzle teal interface
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#716 Activate automatic publication to PyPI upon release
  .github/workflows/publish-to-pypi.yml
Labels: no-changelog-entry-needed

#718 Remove stsci.disttools and d2to1 from azure pipeline env.
  azure-templates.yml
Labels: no-changelog-entry-needed

#715 Simplify logic for archiving WCS in tweakreg
  CHANGELOG.rst
  drizzlepac/buildwcs.py
  drizzlepac/imgclasses.py
  drizzlepac/outputimage.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.help
  drizzlepac/tweakreg.py
  drizzlepac/updatehdr.py
  drizzlepac/util.py
Labels: bug, code cleanup, enhancement, jirahub-ignore

#720 Filter out specific drizzle-generated header keywords so that they will not be included in the "header" sections of SVM QA json files.
  drizzlepac/haputils/diagnostic_utils.py
Labels: enhancement, no-changelog-entry-needed

#721 Catch when HDRNAME is missing
  drizzlepac/haputils/align_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#719 Generate cross-filter point-source comparisons
  drizzlepac/devutils/comparison_tools/starmatch_hist.py
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: enhancement, no-changelog-entry-needed

#699 HAPFigure class in support of HAP graphics
  drizzlepac/haputils/graph_utils.py
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/haputils/svm_quality_graphics.py
  drizzlepac/haputils/wcs_graphics.py
Labels: enhancement, no-changelog-entry-needed

#722 Filter out various header keywords from json file harvesting
  drizzlepac/haputils/diagnostic_json_harvester.py
Labels: enhancement, no-changelog-entry-needed

#726 Add skeleton MVM sequencer for testing
  drizzlepac/runmultihap.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#725 Remove deprecated code
  drizzlepac/haputils/graph_utils.py
Labels: bug, code cleanup, no-changelog-entry-needed

#733 Upgraded the photometry_graphics to use the new API
  drizzlepac/haputils/svm_quality_graphics.py
Labels: code cleanup, no-changelog-entry-needed

#723 Use new API for pipeline Q&A astrometry plots
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/pipeline_graphics.py
  drizzlepac/haputils/quality_analysis.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#734 Add generation of absolute astrometry residuals to pipeline Q&A tests
  drizzlepac/align.py
  drizzlepac/haputils/pipeline_graphics.py
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/testutils.py
  drizzlepac/outputimage.py
  drizzlepac/runastrodriz.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, testing

#738 Updated wcs graphics routines
  drizzlepac/haputils/photometry_graphics.py
  drizzlepac/haputils/svm_quality_graphics.py
  drizzlepac/haputils/wcs_graphics.py
Labels: code cleanup, no-changelog-entry-needed

#739 Update SVM point-to-segment catalog xmatch comparison plots
  drizzlepac/haputils/diagnostic_json_harvester.py
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/svm_quality_graphics.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#742 Fix problems identified in Build 2020.4 testing
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#743 Use EPOCH for GAIADR2 catalog positions
  drizzlepac/haputils/astrometric_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#741 Add interfilter crossmatched residuals graphics
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/haputils/svm_quality_graphics.py
Labels: enhancement, no-changelog-entry-needed

#745 Fix logic for singleton QA Gaia Plotting
  drizzlepac/haputils/quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#746 Fix QA indexing problem
  drizzlepac/haputils/quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#747 Fix runastrodriz errors
  drizzlepac/align.py
  drizzlepac/runastrodriz.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#749 Fix SVM GAIA catalog bugs
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#753 Only try to generate QA JSONs for data with sources
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/quality_analysis.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#755 Update pipeline graphics to only plot valid data
  drizzlepac/haputils/pipeline_graphics.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#754 Remove pysynphot as dependency
  doc/.rtd-environment.yml
  setup.py
Labels: no-changelog-entry-needed

#756 Update to Segmentation SVM processing via use of RickerWavelet kernel for crowded fields
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#748 First draft of SVM documentation framework
  CHANGELOG.rst
  doc/source/astrometry.rst
  doc/source/astrometry_api.rst
  doc/source/hap_glossary.rst
  doc/source/hla.rst
  doc/source/index.rst
  doc/source/runastrodriz.rst
  doc/source/runsinglehap.rst
  doc/source/singlevisit.rst
Labels: Documentation, jirahub-ignore, no-changelog-entry-needed
