Repository spacetelescope/drizzlepac, pull requests merged in 2020-01, with the labels that each got.

#548 Transform HLA classic RA and Dec values into HAP reference frame for better quality sourcelist comparisons
  drizzlepac/devutils/comparison_tools/read_hla/1AAREADME
  drizzlepac/devutils/comparison_tools/read_hla/dods9.csh
  drizzlepac/devutils/comparison_tools/read_hla/hla_test.py
  drizzlepac/devutils/comparison_tools/read_hla/omegaxyz.py
  drizzlepac/devutils/comparison_tools/read_hla/read_hla_catalog.py
  drizzlepac/devutils/comparison_tools/read_hla/read_hla_image.py
  drizzlepac/hapsequencer.py
Labels: annoyance, bug, no-changelog-entry-needed

#558 Issue521 sort poller
  drizzlepac/hlautils/poller_utils.py
Labels: feature request, no-changelog-entry-needed

#562 Close files in align in v3.1.4
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#563 Merge #555 into 3.1.4x branch
  CHANGELOG.rst
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#555 Add rms to headers
  CHANGELOG.rst
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, enhancement

#561 Close open files in align upon error
  drizzlepac/align.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#564 Catch case where all inputs have zero exptime
  drizzlepac/runastrodriz.py
Labels: bug

#568 Fix logic for getting MDRIZTAB pars
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#567 Update SVM processing to use HAP names for input exposures
  drizzlepac/hlautils/analyze.py
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#543 Fix simple poller input
  drizzlepac/hlautils/poller_utils.py
Labels: bug, no-changelog-entry-needed

#569 Add SVM footprint keywords to product headers
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/hlautils/product.py
Labels: enhancement, no-changelog-entry-needed

#553 Implement v1.0 of single fit for entire visit
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/align_utils.py
  drizzlepac/hlautils/astrometric_utils.py
  drizzlepac/hlautils/cell_utils.py
  drizzlepac/hlautils/product.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/user_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/updatehdr.py
Labels: enhancement, no-changelog-entry-needed

#570 Removed last character in the root filename to fix a bug
  drizzlepac/hlautils/processing_utils.py
Labels: bug, no-changelog-entry-needed

#551 Correct problem in tweakback
  drizzlepac/tweakback.py
Labels: bug, no-changelog-entry-needed

#571 compare_sourcelists.py refactor
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/devutils/comparison_tools/read_hla/1AAREADME
  drizzlepac/devutils/comparison_tools/read_hla/dods9.csh
  drizzlepac/devutils/comparison_tools/read_hla/hla_test.py
  drizzlepac/hapsequencer.py
  setup.py
Labels: Documentation, bug, code cleanup, enhancement

#574 Fixed bug in generating the manifest list
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#576 Add init for read_hla package
  drizzlepac/devutils/comparison_tools/read_hla/__init__.py
Labels: bug, code cleanup, no-changelog-entry-needed

#575 Improved the boolean mask creation for use with segmentation catalog
  drizzlepac/hlautils/catalog_utils.py
  drizzlepac/hlautils/product.py
Labels: bug, no-changelog-entry-needed

#577 Retain alignment reference catalog at the end of processing
  drizzlepac/hapsequencer.py
  drizzlepac/hlautils/product.py
Labels: enhancement, no-changelog-entry-needed
