Repository spacetelescope/drizzlepac, pull requests merged in 2021-08, with the labels that each got.

#1091 Update HAPLEVEL for MVM products
  drizzlepac/haputils/product.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1095 Turn off CTX creation for MVM products
  drizzlepac/haputils/product.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1098 Switch to using astropy's bitmask module.
  drizzlepac/buildmask.py
Labels: code cleanup, no-changelog-entry-needed

#1100 Keep using stsci.tools.bitmask for compatibility with numpy 1.21
  drizzlepac/buildmask.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/imgclasses.py
  drizzlepac/processInput.py
  drizzlepac/resetbits.py
  drizzlepac/sky.py
  setup.py
Labels: code cleanup, no-changelog-entry-needed

#1103 Update dependency requirements. Remove unused dependencies
  setup.py
Labels: code cleanup, no-changelog-entry-needed

#1102 Use intrinsic int, bool, and float types instead of numpy
  drizzlepac/adrizzle.py
  drizzlepac/catalogs.py
  drizzlepac/devutils/alignment_viewer.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/haputils/hla_flag_filter_HLAClassic.py
  drizzlepac/imgclasses.py
  drizzlepac/minmed.py
  drizzlepac/stisData.py
  drizzlepac/tweakreg.py
  drizzlepac/tweakutils.py
Labels: code cleanup, no-changelog-entry-needed

#1097 Create code to generate custom mosaics that span multiple skycells
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/make_poller_files.py
  drizzlepac/haputils/product.py
  drizzlepac/make_custom_mosaic.py
Labels: enhancement, no-changelog-entry-needed

#1107 Update some nightly regression tests
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/astroquery_utils.py
  drizzlepac/haputils/testutils.py
  tests/hap/test_align.py
  tests/hap/test_randomlist.py
Labels: bug, testing, no-changelog-entry-needed, jirahub-ignore

#1104 Initial version of MVM tools: find files in the region of interest,
  drizzlepac/haputils/hapcut_utils.py
Labels: feature request, no-changelog-entry-needed, jirahub-ignore

#1109 Fix hap apriori pytest
  drizzlepac/haputils/testutils.py
Labels: bug, testing, no-changelog-entry-needed, jirahub-ignore

#1101 Fix multiprocessing incompatibility with Python >= 3.8
  CHANGELOG.rst
  drizzlepac/adrizzle.py
  drizzlepac/drizCR.py
  drizzlepac/processInput.py
  drizzlepac/util.py
Labels: bug, enhancement

#1096 Update to using PHOTUTILS 1.1.0
  JenkinsfileRT
  azure-templates.yml
  drizzlepac/buildmask.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/deconvolve_utils.py
  setup.py
  tests/hap/test_randomlist.py
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1112 Support general input poller file name
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/processing_utils.py
Labels: enhancement, ready, no-changelog-entry-needed, jirahub-ignore
