Repository spacetelescope/drizzlepac, pull requests merged in 2021-04, with the labels that each got.

#1001 Add weight column to ref catalog for SVM alignment
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/product.py
  setup.py
Labels: enhancement, in progress, jirahub-ignore, no-changelog-entry-needed

#1007 Iterate over SkyMatch options
  CHANGELOG.rst
  drizzlepac/sky.py
Labels: enhancement, jirahub-ignore

#1008 Replaced deprecated STWCS calls
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1006 Enable user epoch selection in creating GAIA catalogs
  drizzlepac/haputils/astrometric_utils.py
Labels: bug, enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#1005 Insure IDCSCALE always exists
  drizzlepac/runastrodriz.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1009 Determine success criteria for MVM alignment fitting
  drizzlepac/align.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: code cleanup, enhancement, no-changelog-entry-needed, parameter update

#1002 WIP: Modified align_to_gaia() method of the FilterProduct to use logic provided by Astrometry WG
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1010 Change API for align.perform_align
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/testutils.py
  drizzlepac/runastrodriz.py
  tests/hap/test_align.py
  tests/hap/test_randomlist.py
Labels: code cleanup, jirahub-ignore, no-changelog-entry-needed, parameter update

#1011 Use correct weights from standardized catalogs
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/product.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1012 Fix support of astrometric catalog names
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/product.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1013 Modified to have a single align_to_gaia method which loops over catalogs, fit methods, and fit geometries
  drizzlepac/haputils/product.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: bug, enhancement, no-changelog-entry-needed

#1014 Apply limits on cross-matches to fit quality
  drizzlepac/align.py
  drizzlepac/haputils/product.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1017 Adjust threshold for point-catalog generation
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1015 Add more diagnostic info to logs
  drizzlepac/haputils/astrometric_utils.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed
