Repository spacetelescope/drizzlepac, pull requests merged in 2021-02, with the labels that each got.

#935 runsinglehap.py documentation cleanup and overall drizzlepac project HTML documenation theme change
  doc/source/conf.py
  doc/source/runsinglehap.rst
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/runsinglehap.py
Labels: Documentation, no-changelog-entry-needed

#936 Update astrometry documentation
  CHANGELOG.rst
  doc/.rtd-environment.yml
  doc/source/astrometry_api.rst
  doc/source/conf.py
  doc/source/index.rst
  doc/source/runastrodriz.rst
  doc/source/runsinglehap.rst
  doc/source/singlevisit.rst
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
Labels: Documentation, enhancement, no-changelog-entry-needed

#934 Add DRIZPARS keyword to drizzle header
  CHANGELOG.rst
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/outputimage.py
  drizzlepac/runastrodriz.py
  drizzlepac/util.py
Labels: enhancement

#929 Set a common active WCS for direct as well as corresponding Grism/Prism images
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
Labels: enhancement, no-changelog-entry-needed

#940 Added xfail to two tests to force a release candidate build.
  tests/hap/test_align.py
  tests/hap/test_apriori.py
Labels: bug, no-changelog-entry-needed, testing

#941 Clean up manifest file and disk as necessary
  drizzlepac/hapsequencer.py
Labels: bug, code cleanup, no-changelog-entry-needed

#944 Store FITS keyword WCS solutions as a dictionary for use in multiple routines
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/poller_utils.py
Labels: bug, no-changelog-entry-needed

#942 Fix errors found in 1k dataset test
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/deconvolve_utils.py
  setup.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed, ready

#947 Singlevisit documentation update
  doc/source/catalog_generation.rst
  doc/source/runsinglehap.rst
  doc/source/singlevisit.rst
  drizzlepac/devutils/sourcelist_flag_breakdown.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/generate_custom_svm_param_file.py
  drizzlepac/haputils/photometry_tools.py
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
Labels: Documentation, code cleanup, enhancement, no-changelog-entry-needed, parameter update

#943 Update alignment functions docstrings
  doc/source/astrometry_api.rst
  drizzlepac/align.py
Labels: Documentation, jirahub-ignore, no-changelog-entry-needed

#946 Handle situation of no viable Total Data Products in the visit
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/poller_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed
