Repository spacetelescope/drizzlepac, pull requests merged in 2021-01, with the labels that each got.

#906 Add DRIZCORR as rejection criteria
  drizzlepac/haputils/analyze.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#910 Add S_REGION to FLC files
  drizzlepac/runastrodriz.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#911 MVM: Only generate sky cell layers being updated by input exposures
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/poller_utils.py
Labels: bug, enhancement, no-changelog-entry-needed

#913 Fix a bug in tweakback due to which updated WCS's name is ignored
  CHANGELOG.rst
  drizzlepac/tweakback.py
Labels: bug

#907 Insure all processing results in updated WCSs
  drizzlepac/runastrodriz.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#927 Update version info from 3.2.x
  CHANGELOG.rst
Labels: code cleanup

#926 Fix HAPEXPNAME in HDRTAB for EXP HAP Products
  drizzlepac/haputils/processing_utils.py
Labels: jirahub-ignore, no-changelog-entry-needed, ready

#917 Address problem of the deblend step taking too long
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: code cleanup, investigation, no-changelog-entry-needed
