Repository spacetelescope/drizzlepac, pull requests merged in 2021-05, with the labels that each got.

#1016 Insure correct versions get reported for WCS
  drizzlepac/haputils/align_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1018 Clarified message issued when a downgrade in the fit geometry is done.
  drizzlepac/haputils/product.py
Labels: bug

#1023 Add logic to avoid relative fit with singletons
  drizzlepac/haputils/product.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1027 Update default fit pars
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, parameter update

#1029 Update defaults for pipeline catalog use
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: jirahub-ignore, no-changelog-entry-needed, parameter update

#1028 Update inputs for fitting
  doc/.rtd-environment.yml
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/graph_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/imageObject.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/wcs_functions.py
  setup.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1032 Update CHANGE log and RTD docs for next release
  CHANGELOG.rst
  doc/source/astrometry_api.rst
  doc/source/conf.py
  doc/source/index.rst
  drizzlepac/align.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/pixreplace.py
  drizzlepac/wcs_functions.py
Labels: Documentation

#1033 Skip inconsistent fits during relative alignment
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/product.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1038 Refactor code in updatewcs_with_shift
  drizzlepac/updatehdr.py
Labels: code cleanup, no-changelog-entry-needed
