Repository spacetelescope/drizzlepac, pull requests merged in 2021-06, with the labels that each got.

#1045 Correct astrodrizzle example use of the wcskey
  drizzlepac/astrodrizzle.help
Labels: Documentation, no-changelog-entry-needed

#1047 Initialize fit for each attempt
  drizzlepac/align.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1046 Insure IDCTAB is current in FLT files
  drizzlepac/runastrodriz.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1048 Fix memory corruption in the linear blot algorithm
  CHANGELOG.rst
  src/cdrizzleblot.c
Labels: bug

#1043 Define bounded WCS for SkyCell footprint
  drizzlepac/haputils/cell_utils.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1049 Minimize memory usage of SkyFootprint
  drizzlepac/haputils/cell_utils.py
Labels: bug, enhancement, jirahub-ignore, no-changelog-entry-needed

#1051 WIP: Changes made to use the "bounding box WCS"
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
  setup.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1056 Fix list input parsing for get_sky_cells
  drizzlepac/haputils/cell_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1057 Fixed abbreviated "long string" values in the FITS header
  drizzlepac/outputimage.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1058 Initialize the SkyFootprint attribute, self.footprint_member
  drizzlepac/haputils/cell_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1059 Fix incorrect MVM skycell/projection cell identification bug
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/poller_utils.py
Labels: bug, code cleanup, no-changelog-entry-needed
