Repository spacetelescope/drizzlepac, pull requests merged in 2021-07, with the labels that each got.

#1061 Fixed the clean up of the Rules files
  drizzlepac/hapmultisequencer.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1064 Remove unused variable `var`
  src/arrdrizmodule.c
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1065 Fix indexing of SkyCell IDs
  drizzlepac/haputils/cell_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1067 WIP: Address unreasonable deblending times for segments
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1070 Fix the construction of the manifest filename for MVM processing
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/product.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed

#1072 Update docs for aqutils
  drizzlepac/haputils/astroquery_utils.py
Labels: Documentation, code cleanup, enhancement, jirahub-ignore, no-changelog-entry-needed

#1073 Fix the code in cell_utils.py which is generating a FutureWarning
  drizzlepac/haputils/cell_utils.py
Labels: annoyance, jirahub-ignore, no-changelog-entry-needed

#1071 Remove indirect dependencies
  doc/.rtd-environment.yml
  setup.py
Labels: code cleanup, enhancement, jirahub-ignore, no-changelog-entry-needed

#1076 Fix MVM poller
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
Labels: bug, enhancement, jirahub-ignore, no-changelog-entry-needed

#1075 Reset parameters for shift alignment
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: bug, jirahub-ignore, no-changelog-entry-needed, parameter update

#1077 Skip drizzlepac PyTests for HSTDP-2021.3.3. Build
  tests/acs/test_acs_kernels.py
  tests/acs/test_acs_narrowband.py
  tests/acs/test_acs_tweak.py
  tests/acs/test_asn_regress.py
  tests/acs/test_unit.py
  tests/hap/test_align.py
  tests/hap/test_alignpipe_randomlist.py
  tests/hap/test_apriori.py
  tests/hap/test_pipeline.py
  tests/hap/test_randomlist.py
  tests/stis/test_stis.py
  tests/wfc3/test_vary_perf.py
  tests/wfc3/test_wfc3.py
  tests/wfpc2/test_wfpc2.py
Labels: jirahub-ignore, no-changelog-entry-needed, testing

#1080 Fix to handle an undefined manifest filename
  drizzlepac/hapsequencer.py
Labels: annoyance, bug, jirahub-ignore, no-changelog-entry-needed

#1078 Only apply DRIZPARS when returned by tweakwcs
  drizzlepac/runastrodriz.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1079 Fix fitgeom use in log msg
  drizzlepac/haputils/align_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1081 Fixed bug to access the dataset filenames properly AND remove zero exposure images from processing
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/analyze.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1085 Create Drizzled MVM FLC files
  drizzlepac/hapmultisequencer.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#1088 MVM: Skip any image/chip in the MVM visit list with no skycell overlap
  drizzlepac/haputils/cell_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#1087 Allow local files in poller files
  drizzlepac/haputils/make_poller_files.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed
