Repository spacetelescope/drizzlepac, pull requests merged in 2021-03, with the labels that each got.

#953 Updated the SVM user documentation
  doc/source/catalog_generation.rst
  doc/source/conf.py
  doc/source/singlevisit.rst
Labels: Documentation, code cleanup, jirahub-ignore, no-changelog-entry-needed

#954 Fix EXTNAME/EXTVER in simple FITS files
  CHANGELOG.rst
  drizzlepac/outputimage.py
Labels: bug, jirahub-ignore

#956 Improved the way WCS solutions are manipulated for visits with Grism/Prism data
  drizzlepac/hapsequencer.py
Labels: bug, enhancement, jirahub-ignore, no-changelog-entry-needed

#951 Redo S_REGION computation
  drizzlepac/align.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/processing_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed, ready

#958 Ensure diagnostic files do not get created during standard processing
  drizzlepac/haputils/catalog_utils.py
Labels: bug, code cleanup, jirahub-ignore, no-changelog-entry-needed

#962 New SREGION computation based on WCS footprint
  drizzlepac/haputils/cell_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed, ready

#963 Debugging issues with archiving and restoring WCS solutions from headerlets
  drizzlepac/hapsequencer.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#966 Insure HDRNAME is always valid
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/processing_utils.py
Labels: enhancement, jirahub-ignore, no-changelog-entry-needed, ready

#965 Add more error cases for FWHM use
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/deconvolve_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#971 Fix bugs in point-catalog generation
  drizzlepac/haputils/deconvolve_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#969 Ensure the PHOT keywords can be found in the SVM product header
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/processing_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#972 Correct computation of CR threshold factor
  drizzlepac/hapsequencer.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#964 Make MVM test datasets
  drizzlepac/devutils/search_skyframes.py
  drizzlepac/haputils/make_poller_files.py
Labels: enhancement, no-changelog-entry-needed

#974 Fixed the logic with regard to "reject_catalogs" and "diagnostic mode".
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#976 Fix svm qa logic
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#983 Reset a column to its original name "RA" from the temporary name of "#RA"
  drizzlepac/haputils/svm_quality_analysis.py
  setup.py
Labels: bug, jirahub-ignore, no-changelog-entry-needed

#986 Update default astrometry catalogs used for a posteriori processing
  drizzlepac/align.py
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/runhap.config
Labels: code cleanup, enhancement, no-changelog-entry-needed

#996 Updates to catalog columns
  drizzlepac/haputils/catalog_utils.py
Labels: code cleanup, no-changelog-entry-needed

#1000 Deleted obsolete modules from drizzlepac repository
  drizzlepac/devutils/sourcelist_generation.py
  drizzlepac/haputils/se_source_generation.py
Labels: code cleanup, no-changelog-entry-needed
