Repository spacetelescope/drizzlepac, pull requests merged in 2021-09, with the labels that each got.

#1106 Compute mvm sregion
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/processing_utils.py
  drizzlepac/haputils/product.py
Labels: enhancement, ready, no-changelog-entry-needed, jirahub-ignore

#1115 SVM: Handle multiple total data products (TDP) when first TDP processed has no sources
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1116 Fix amutils after update to PHOTUTILS 1.1.0
  drizzlepac/haputils/astrometric_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1117 Remove reference to source_properties
  drizzlepac/haputils/astrometric_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1118 Update pyproject to use oldest-supported-numpy
  LICENSE.txt
  pyproject.toml
  setup.cfg
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1123 Add build-backend to pyproject.toml, to force PEP517 build (#1121)
  pyproject.toml
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1124 Revert to using current numpy only for build
  pyproject.toml
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1125 MVM: Insure SVM-derived WCS gets used as input to MVM processing
  drizzlepac/devutils/search_skyframes.py
  drizzlepac/haputils/make_poller_files.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/haputils/which_skycell.py
  drizzlepac/make_custom_mosaic.py
Labels: enhancement, no-changelog-entry-needed

#1128 which_skycell.py simple bugfix
  drizzlepac/haputils/which_skycell.py
Labels: bug, no-changelog-entry-needed

#1131 Only deblend large sources
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: enhancement, ready, no-changelog-entry-needed, jirahub-ignore

#1122 Generate empty source catalogs
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/product.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1132 Function mvm_analyze_wrapper determines the viability of an image for MVM processing
  drizzlepac/haputils/analyze.py
Labels: feature request, no-changelog-entry-needed, jirahub-ignore

#1133 MVM: Make alignment to GAIA optional
  drizzlepac/hapmultisequencer.py
  drizzlepac/make_custom_mosaic.py
  drizzlepac/runmultihap.py
Labels: enhancement, no-changelog-entry-needed

#1129 Minimize use of fitting for shift only
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/astroquery_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1136 Add FWHM measurement to the output Segmentation filter catalogs
  drizzlepac/haputils/catalog_utils.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1138 Improve make_poller_files.py
  drizzlepac/haputils/make_poller_files.py
Labels: bug, enhancement, code cleanup, no-changelog-entry-needed

#1142 Add the Kron radius as an output measurement for the catalog
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/default_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/default_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1143 Update change log for v3.3.0
  CHANGELOG.rst
Labels: Documentation, jirahub-ignore

#1145 Fix numpy requirement for release
  pyproject.toml
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1146 Fixed a bug which caused the proper naming of the output manifest
  drizzlepac/hapsequencer.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1144 MVM: create documentation page for custom mosaic creation code
  doc/source/index.rst
  doc/source/makecustommosaic.rst
  doc/source/multivisit.rst
  doc/source/runmultihap.rst
  doc/source/runsinglehap.rst
  drizzlepac/haputils/make_poller_files.py
  drizzlepac/haputils/which_skycell.py
  drizzlepac/make_custom_mosaic.py
  drizzlepac/runmultihap.py
Labels: Documentation, code cleanup, no-changelog-entry-needed
