Repository spacetelescope/drizzlepac, pull requests merged in 2022-03, with the labels that each got.

#1252 Simplify machinery for rendering help or doc strings
  doc/source/ablot.rst
  doc/source/adrizzle.rst
  doc/source/astrodrizzle.rst
  doc/source/drizcr.rst
  doc/source/imagefindpars.rst
  doc/source/pixreplace.rst
  doc/source/pixtopix.rst
  doc/source/pixtosky.rst
  doc/source/refimagefindpars.rst
  doc/source/skytopix.rst
  doc/source/static.rst
  doc/source/tweakback.rst
  doc/source/tweakreg.rst
  doc/source/updatenpol.rst
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/buildwcs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/imagefindpars.py
  drizzlepac/mapreg.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/refimagefindpars.py
  drizzlepac/resetbits.py
  drizzlepac/sky.py
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
Labels: Documentation, no-changelog-entry-needed

#1272 Add mvm docs to describe MVM processing steps
  doc/source/images/SkyCell_numbering.png
  doc/source/images/figure_aitoff.png
  doc/source/images/figure_pole.png
  doc/source/images/pg1202_acs_wfc3_mast_footprint.png
  doc/source/index.rst
  doc/source/multivisit.rst
  doc/source/multivisit_api.rst
  drizzlepac/haputils/cell_utils.py
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1282 Update requirements to allow astropy 5.0 use (#1280)
  pyproject.toml
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1251 Update Release Notes for v3.4.0 release
  CHANGELOG.rst
Labels: Documentation, jirahub-ignore

#1283 Add release notes for v3.4.0
  CHANGELOG.rst
Labels: Documentation, jirahub-ignore, build

#1286 Limit markupsafe version for astropy use
  setup.cfg
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore, build

#1288 Limit markupsafe version for astropy use (#1286)
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1285 Reset tasknames to work with TEAL
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/buildmask.py
  drizzlepac/buildwcs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/imagefindpars.py
  drizzlepac/mapreg.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/refimagefindpars.py
  drizzlepac/resetbits.py
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
Labels: bug, Documentation, no-changelog-entry-needed, jirahub-ignore

#1289 Reset tasknames to work with TEAL (#1285)
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/astrodrizzle.py
  drizzlepac/buildmask.py
  drizzlepac/buildwcs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/imagefindpars.py
  drizzlepac/mapreg.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/refimagefindpars.py
  drizzlepac/resetbits.py
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1290 Lower markupsafe dependency again
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1291 Lower markupsafe dependency again (#1290)
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1294 Update pyproject file for public release (#1293)
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1295 Protect computations when photflam is equal to 0.0
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/constants.py
  drizzlepac/haputils/photometry_tools.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1297 Remove IPPPSSOO keyword from MVM product headers (again)
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/product.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1299 Use modified publish script for release
  .github/workflows/publish-to-pypi.yml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1292 Fix problem with astropy 5.0 table interpretation
  drizzlepac/processInput.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1300 Statistics for SVM and MVM
  drizzlepac/haputils/product.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1306 Fix setup.py
  setup.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1307 Explicitly update boolean column in ASN tables
  drizzlepac/processInput.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1308 Update for 341rc3
  drizzlepac/processInput.py
  setup.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1313 Refine HAP Pytests success criteria
  tests/hap/test_svm_ibqk07.py
  tests/hap/test_svm_ibyt50.py
  tests/hap/test_svm_j97e06.py
Labels: testing, no-changelog-entry-needed, jirahub-ignore

#1312 Synchronize output WCS specifications for SVM processing
  drizzlepac/haputils/product.py
  drizzlepac/wcs_functions.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1309 Ignore git information for installations in conda envs
  drizzlepac/haputils/comparison_utils.py
  drizzlepac/haputils/get_git_rev_info.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, ready, no-changelog-entry-needed, jirahub-ignore

#1317 Update for rc4
  azure-templates.yml
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/comparison_utils.py
  drizzlepac/haputils/get_git_rev_info.py
  drizzlepac/haputils/product.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/wcs_functions.py
  tests/hap/test_svm_ibqk07.py
  tests/hap/test_svm_ibyt50.py
  tests/hap/test_svm_j97e06.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1316 Ensure units of catalog variables comply with Astropy
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1318 Modify the units of the catalog variables to put them into a format (…
  drizzlepac/haputils/catalog_utils.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1319 Apply default alignment fit parameters for zero exptime exposures
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1320 Fix bug caused by Astropy Tables being interpreted as QTables
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1323 Revise logic for when mask keywords are computed
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/product.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1326 Restrict version of Photutils to < 1.4.0.
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1324 Add MEANWHT and MEDWHT keywords to drizzle products
  drizzlepac/haputils/product.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore
