Repository spacetelescope/drizzlepac, pull requests merged in 2022-09, with the labels that each got.

#1433 Insure correct filetype gets defined for filter and total products
  CHANGELOG.rst
  azure-templates.yml
  drizzlepac/haputils/poller_utils.py
Labels: enhancement, jirahub-ignore

#1434 Update to fully support numpy v1.23
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/cell_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1435 Update release candidate to define v3.5.0rc1
  CHANGELOG.rst
  azure-templates.yml
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/poller_utils.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1436 Remove Python 3.7 tests from Jenkins builds
  JenkinsfileRT
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1438 Make sure WFPC2 parameter files get installed
  setup.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1437 Add GitHub actions
  .flake8
  .github/workflows/ci.yml
  MANIFEST.in
  README.md
  azure-pipelines.yml
  azure-templates.yml
  doc/source/conf.py
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore, build

#1440 use canonical filename of RTD configuration and enable `nitpicky`
  .readthedocs.yaml
  .readthedocs.yml
  doc/source/conf.py
Labels: no-changelog-entry-needed

#1441 Prevent astroquery code from throwing an Exception for SVM requests
  drizzlepac/haputils/astroquery_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1444 Fix command line interface for runastrodriz
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1443 Use verify_guiding correctly for pipeline and SVM processing
  CHANGELOG.rst
  drizzlepac/haputils/analyze.py
  drizzlepac/runastrodriz.py
Labels: bug, enhancement, jirahub-ignore

#1445 Fix command line interface for runastrodriz (#1444)
  drizzlepac/runastrodriz.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1446 Implement update of WFPC2 header for best references in runastrodriz
  drizzlepac/runastrodriz.py
  drizzlepac/wfpc2Data.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore
