Repository spacetelescope/drizzlepac, pull requests merged in 2022-07, with the labels that each got.

#1410 Visualize results of overlap crossmatch analysis from mvm_quality_analysis.py
  drizzlepac/haputils/graph_utils.py
  drizzlepac/haputils/mvm_quality_analysis.py
  drizzlepac/haputils/mvm_quality_graphics.py
Labels: enhancement, no-changelog-entry-needed

#1412 Update runastrodriz to work with WFPC2 singletons
  drizzlepac/align.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/config_utils.py
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/processing_utils.py
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_n1.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_quality_control_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2_pc_index.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_n1.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_quality_control_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2_pc_index.json
  drizzlepac/pars/wfpc2_header_hap.rules
  drizzlepac/pars/wfpc2_mvm_header_hap.rules
  drizzlepac/pars/wfpc2_mvm_single_header_hap.rules
  drizzlepac/pars/wfpc2_single_header_hap.rules
  drizzlepac/runastrodriz.py
  drizzlepac/wfpc2Data.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1413 MVM: Update cross-match routine to read pipeline poller file
  drizzlepac/haputils/mvm_quality_analysis.py
Labels: bug, no-changelog-entry-needed

#1414 Exit immediately if no new MVM inputs
  drizzlepac/haputils/poller_utils.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1411 Revert sky matching upon any error
  drizzlepac/sky.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1419 Added try/except blocks for exceptions generated with regions do not have cross matches
  drizzlepac/haputils/mvm_quality_analysis.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore
