Repository spacetelescope/drizzlepac, pull requests merged in 2022-01, with the labels that each got.

#1232 Add explicit dependency on spherical-geometry and set min version
  doc/.rtd-environment.yml
  setup.py
Labels: bug, no-changelog-entry-needed

#1233 Update apriori test to be more explicit with errors
  drizzlepac/haputils/testutils.py
  tests/hap/test_apriori.py
Labels: testing, no-changelog-entry-needed, jirahub-ignore

#1234 Update apriori test to be more explicit with errors (#1233)
  drizzlepac/haputils/testutils.py
  tests/hap/test_apriori.py
Labels: testing, no-changelog-entry-needed, jirahub-ignore

#1235 Add explicit dependency on spherical-geometry and set min version (#1…
  doc/.rtd-environment.yml
  setup.py
Labels: no-changelog-entry-needed, jirahub-ignore

#1238 Insure both FLT and FLC headers have same a posteriori fit keywords
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1221 update how make_poller_files.py generates visit numbers to account an edge case
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/make_poller_files.py
Labels: bug, no-changelog-entry-needed

#1243 Fix logic to not align grism data in standard pipeline
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/product.py
Labels: bug, no-changelog-entry-needed

#1246 RickerWavelet Kernel for SBC needs to have dimensions which are odd
  drizzlepac/pars/hap_pars/default_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1244 Build process
  CHANGELOG.rst
  MANIFEST.in
  doc/source/conf.py
  drizzlepac/__init__.py
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/align.py
  drizzlepac/astrodrizzle.py
  drizzlepac/buildwcs.py
  drizzlepac/catalogs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/generate_custom_svm_param_file.py
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/which_skycell.py
  drizzlepac/imageObject.py
  drizzlepac/imagefindpars.py
  drizzlepac/linearfit.py
  drizzlepac/make_custom_mosaic.py
  drizzlepac/mapreg.py
  drizzlepac/mdriz.py
  drizzlepac/minmed.py
  drizzlepac/outputimage.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/quickDeriv.py
  drizzlepac/refimagefindpars.py
  drizzlepac/regfilter.py
  drizzlepac/resetbits.py
  drizzlepac/runastrodriz.py
  drizzlepac/runmultihap.py
  drizzlepac/runsinglehap.py
  drizzlepac/sky.py
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatehdr.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: build, ready-for-final-review

#1250 Remove logic from align
  drizzlepac/align.py
Labels: bug, ready, no-changelog-entry-needed, jirahub-ignore

#1241 MVM: Make tool to quantify quality of GAIA alignment generic for general use
  drizzlepac/devutils/analyze_mvm_gaia_alignment.py
Labels: enhancement, no-changelog-entry-needed

#1222 Fix incorrect drizzling of 0-weight input pixels
  CHANGELOG.rst
  src/cdrizzlebox.c
  tests/drizzle/test_drizzle.py
Labels: bug
