Repository spacetelescope/drizzlepac, pull requests merged in 2022-05, with the labels that each got.

#1357 Improve algorithm for identifying and filtering large segments
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1355 Carry over IDCSCALE keyword when updating WCS to match Grism WCS
  drizzlepac/hapsequencer.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1360 Ignore layers with no overlapping exposures
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/product.py
Labels: bug, no-changelog-entry-needed

#1362 Update crder units
  drizzlepac/haputils/align_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1363 Generate 342rc0
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/pars/acs_mvm_header_hap.rules
  drizzlepac/runastrodriz.py
  pyproject.toml
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1365 This change addresses bugs associated with the big_segments attribute of the segmentation image
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1366 Update the WFC3 rules files -- MERGE after PR#1365
  drizzlepac/pars/wfc3_header_hap.rules
  drizzlepac/pars/wfc3_mvm_header_hap.rules
  drizzlepac/pars/wfc3_mvm_single_header_hap.rules
  drizzlepac/pars/wfc3_single_header_hap.rules
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1368 Only allow "verify_guiding" check for MVM processing
  drizzlepac/haputils/analyze.py
  drizzlepac/runastrodriz.py
Labels: feature request, no-changelog-entry-needed, parameter update, jirahub-ignore

#1371 Fix the size of the HAPEXPNAME column in the HDRTAB of the MVM output DRZ/DRZ file
  drizzlepac/haputils/processing_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1370 Pass along default WCSNAME
  drizzlepac/outputimage.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1373 Generate 342rc1
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/processing_utils.py
  drizzlepac/pars/wfc3_header_hap.rules
  drizzlepac/pars/wfc3_mvm_header_hap.rules
  drizzlepac/pars/wfc3_mvm_single_header_hap.rules
  drizzlepac/pars/wfc3_single_header_hap.rules
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1372 Re-design tweakback
  CHANGELOG.rst
  drizzlepac/tweakback.py
Labels: bug, Documentation

#1374 Remove implementation of bad_guiding check
  drizzlepac/haputils/analyze.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore, build

#1378 Updates to create the MVM quality analysis infrastructure
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/mvm_quality_analysis.py
  drizzlepac/haputils/poller_utils.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore
