Repository spacetelescope/drizzlepac, pull requests merged in 2022-04, with the labels that each got.

#1327 Update 341final
  doc/source/images/mvm_p0498x16y19_f555w.png
  doc/source/images/skycell-p1889x07y19_f105w_full.jpg
  doc/source/images/skycell-p1889x07y19_f775w_full.jpg
  doc/source/images/skycell_p0080x09y16-slewing-example-color.jpg
  doc/source/index.rst
  doc/source/multivisit.rst
  doc/source/multivisit_api.rst
  doc/source/multivisit_products.rst
  doc/source/runmultihap.rst
  doc/source/runsinglehap.rst
  doc/source/singlevisit.rst
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/generate_custom_svm_mvm_param_file.py
  drizzlepac/haputils/product.py
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1328 Add release notes for 3.4.1final
  CHANGELOG.rst
Labels: Documentation, jirahub-ignore, build

#1329 Add release notes for 3.4.1final (#1328)
  CHANGELOG.rst
Labels: Documentation, jirahub-ignore, build

#1330 Pull changes from #1299 to master
  .github/workflows/publish-to-pypi.yml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1331 Pull changes from #1299 to master (#1330)
  .github/workflows/publish-to-pypi.yml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1332 Fix typo in ACS MVM header rules file
  drizzlepac/pars/acs_mvm_header_hap.rules
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1335 Update astropy min version to 5.0.4
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1349 Clarify comment portion of FITS card for MEANWHT and MEDWHT.
  drizzlepac/haputils/product.py
Labels: bug, Documentation, no-changelog-entry-needed, jirahub-ignore

#1333 Avoid archiving duplicate WCS solutions in SVM processing
  drizzlepac/hapsequencer.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1354 Update installation dependencies for fitsblender and skypac
  setup.cfg
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1351 Flag and ignore bad images based on detecting linear features
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review
