Repository spacetelescope/drizzlepac, pull requests merged in 2022-02, with the labels that each got.

#1264 Update toml file to for NumPy support
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1265 Generate correct HDRNAME (finally?)
  drizzlepac/haputils/align_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1267 SVM/MVM: Update/fix HAP code "exit" statement handling
  drizzlepac/devutils/comparison_tools/compare_sourcelists.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/comparison_utils.py
  drizzlepac/haputils/config_utils.py
  drizzlepac/haputils/get_git_rev_info.py
  drizzlepac/haputils/product.py
Labels: enhancement, no-changelog-entry-needed

#1262 Improve source detection for SBC data
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/processing_utils.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1256 Remove extraneous version variables
  drizzlepac/align.py
  drizzlepac/buildwcs.py
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/generate_custom_svm_param_file.py
  drizzlepac/haputils/pandas_utils.py
  drizzlepac/haputils/which_skycell.py
  drizzlepac/linearfit.py
  drizzlepac/make_custom_mosaic.py
  drizzlepac/mapreg.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/regfilter.py
  drizzlepac/resetbits.py
  drizzlepac/runastrodriz.py
  drizzlepac/runmultihap.py
  drizzlepac/runsinglehap.py
  drizzlepac/skytopix.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatehdr.py
  drizzlepac/updatenpol.py
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1271 Change to using relative version imports
  drizzlepac/align.py
  drizzlepac/buildwcs.py
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/mapreg.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/resetbits.py
  drizzlepac/runastrodriz.py
  drizzlepac/skytopix.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatenpol.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1269 Add product rules files for deletion
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1273 Figures for the MVM utilities descriptions
  doc/source/SkyCell14_14.png
  doc/source/SkyCell14_15.png
  doc/source/SkyCellCombo.png
  doc/source/ZoomSkyCellCombo.png
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1278 Protect actions being performed on a potentially NoneType object
  drizzlepac/align.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1274 Modified three tests to remove the "skip" to enable the tests to execute
  conftest.py
  tests/hap/svm_input.lst
  tests/hap/test_alignpipe_randomlist.py
  tests/hap/test_pipeline.py
  tests/hap/test_randomlist.py
  tests/hap/test_run_svmpoller.py
  tests/hap/test_svm_j97e06.py
  tests/hap/test_svm_wfc3ir.py
Labels: in progress, testing, no-changelog-entry-needed, jirahub-ignore

#1280 Update requirements to allow astropy 5.0 use
  pyproject.toml
  setup.cfg
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1279 Generate SVM QA JSONs again
  drizzlepac/haputils/diagnostic_utils.py
  drizzlepac/haputils/get_git_rev_info.py
  drizzlepac/haputils/svm_quality_analysis.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore
