Repository spacetelescope/drizzlepac, pull requests merged in 2022-10, with the labels that each got.

#1447 Add runastrodriz manifests
  drizzlepac/hapsequencer.py
  drizzlepac/runastrodriz.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1450 SVM: Fix logic for catalogs and cosmic ray checking
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1452 small change to test PEP517 build of C extension
  setup.py
Labels: bug, build

#1451 Add error handling/improved messages to CatalogSearch functions
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
Labels: enhancement, no-changelog-entry-needed, jirahub-ignore

#1454 Add the missing CHANGELOG comment for PR#1450
  CHANGELOG.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1466 Protect against there being no sources left to measure
  CHANGELOG.rst
  drizzlepac/haputils/analyze.py
Labels: bug, jirahub-ignore

#1465 Cleanup SCI header (FLT/C, DRZ/C) keywords remaining from an 'a aposteriori' active WCS solution
  CHANGELOG.rst
  drizzlepac/hapsequencer.py
Labels: bug, code cleanup, jirahub-ignore
