Repository spacetelescope/drizzlepac, pull requests merged in 2023-07, with the labels that each got.

#1551 Update code to update WPFC2 chip gaps
  drizzlepac/buildmask.py
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_total.json
Labels: no-changelog-entry-needed, parameter update, jirahub-ignore

#1616 HlA-1059: Reference catalog weights corrected
  drizzlepac/haputils/product.py
Labels: jirahub-ignore

#1617 HLA-1052: Updated WFPC2 drizzle parameters for HAP
  drizzlepac/haputils/config_utils.py
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n1.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n2.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n3.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n4.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_total.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2_wfpc2_index.json
Labels: jirahub-ignore

#1614 Fixed bug in calculation of the measurements for each detected source
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore

#1629 WFPC2 json file error due to trailing comma
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2_wfpc2_index.json
Labels: bug, no-changelog-entry-needed, jirahub-ignore
