Repository spacetelescope/drizzlepac, pull requests merged in 2023-09, with the labels that each got.

#1659 remove unsupported `system_packages` RTD config setting
  .readthedocs.yaml
Labels: no-changelog-entry-needed

#1658 HLA-1084:Fix regression tests
  JenkinsfileRT
  requirements-dev.txt
Labels: testing, no-changelog-entry-needed

#1667 SCSB-93: Changes to fix errors expected from Numpy 2.0
  drizzlepac/haputils/cell_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1669 HLA-1122: Added log for astrometric catalog source
  drizzlepac/haputils/astrometric_utils.py
Labels: enhancement, no-changelog-entry-needed

#1674 Added or improved some log messages.
  drizzlepac/align.py
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore
