Repository spacetelescope/drizzlepac, pull requests merged in 2023-05, with the labels that each got.

#1549 Fix a bug in buildFileListOrig causing crash when updatewcs=True
  CHANGELOG.rst
  drizzlepac/processInput.py
Labels: bug

#1552 runastrodriz: Report the name of the file being process on exception
  drizzlepac/runastrodriz.py
Labels: bug, annoyance

#1553 test against pre-built binaries of `numpy`
  requirements-dev.txt
Labels: no-changelog-entry-needed

#1547 Protect against using compute_sregion for no valid images
  CHANGELOG.rst
  drizzlepac/processInput.py
  drizzlepac/runastrodriz.py
Labels: bug

#1542 Unit test for point kernel
  tests/drizzle/cdriz_setup.py
  tests/drizzle/test_cdriz.py
  tests/drizzle/test_drizzle.py
  tests/drizzle/test_kernel.py
  tests/drizzle/truth_files/edge_gaussian_truth.csv
  tests/drizzle/truth_files/gaussian_truth.csv
  tests/drizzle/truth_files/lanczos3_truth.csv
  tests/drizzle/truth_files/large_square_gaussian_truth.csv
  tests/drizzle/truth_files/nonsymmetrical_gaussian_truth.csv
  tests/drizzle/truth_files/point_truth.csv
  tests/drizzle/truth_files/square_truth.csv
  tests/drizzle/truth_files/turbo_truth.csv
Labels: in progress, no-changelog-entry-needed, jirahub-ignore

#1550 WFPC2: Issue a specific error code and create an empty manifest file for bad data
  CHANGELOG.rst
  drizzlepac/runastrodriz.py
Labels: enhancement

#1556 Fix changelog
  CHANGELOG.rst
Labels: Documentation, code cleanup

#1557 Newcandidate 360rc1
  CHANGELOG.rst
  drizzlepac/processInput.py
  drizzlepac/runastrodriz.py
  requirements-dev.txt
  tests/drizzle/cdriz_setup.py
  tests/drizzle/test_cdriz.py
  tests/drizzle/test_drizzle.py
  tests/drizzle/test_kernel.py
  tests/drizzle/truth_files/edge_gaussian_truth.csv
  tests/drizzle/truth_files/gaussian_truth.csv
  tests/drizzle/truth_files/lanczos3_truth.csv
  tests/drizzle/truth_files/large_square_gaussian_truth.csv
  tests/drizzle/truth_files/nonsymmetrical_gaussian_truth.csv
  tests/drizzle/truth_files/point_truth.csv
  tests/drizzle/truth_files/square_truth.csv
  tests/drizzle/truth_files/turbo_truth.csv
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1561 Five PyTests have had their rtol/atol settings loosened
  tests/acs/test_asn_regress.py
  tests/stis/test_stis.py
  tests/wfc3/test_wfc3.py
  tests/wfpc2/test_wfpc2.py
Labels: testing, no-changelog-entry-needed, jirahub-ignore

#1559 Modified the criteria for catalog rejection based upon expected CR contamination
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore

#1562 Newcandidate 360rc2
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/allsky_cells.fits
  requirements-dev.txt
  tests/acs/test_asn_regress.py
  tests/stis/test_stis.py
  tests/wfc3/test_wfc3.py
  tests/wfpc2/test_wfpc2.py
  tox.ini
Labels: no-changelog-entry-needed, jirahub-ignore, build
