Repository spacetelescope/drizzlepac, pull requests merged in 2023-08, with the labels that each got.

#1638 Drizzlepac: Ensure the "best" WCS solution is found when using a set
  drizzlepac/runastrodriz.py
Labels: bug, jirahub-ignore

#1639 Drizzlepac: Updated PyTest test_svm_hrcsbc.py from causing failure on PR
  tests/hap/test_svm_hrcsbc.py
Labels: no-changelog-entry-needed, jirahub-ignore

#1632 HLA-1060: Fix formerly working HAP PyTest in test_align.py
  drizzlepac/align.py
  tests/hap/test_align.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1644 Updates to JenkinsfileRT as suggested by Nadia and Joe.
  JenkinsfileRT
Labels: bug, jirahub-ignore

#1646 Removed XFAIL marker as tests are xpassing
  tests/acs/test_acs_tweak.py
  tests/acs/test_unit.py
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1649 Removed version restriction on Matplotlib
  pyproject.toml
Labels: code cleanup, jirahub-ignore

#1650 Get the CHANGELOG.rst from the last release (3.6.1)
  CHANGELOG.rst
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1612 Allow group specifications as integers or tuples
  CHANGELOG.rst
  drizzlepac/imageObject.py
  drizzlepac/processInput.py
  drizzlepac/util.py
Labels: bug

#1651 Updated CHANGELOG
  CHANGELOG.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1655 HLA-1093: Updated WFPC2 params for SVM any_n1.json and any_n2.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n1.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/wfpc2/wfpc2_wfpc2_astrodrizzle_any_n2.json
Labels: no-changelog-entry-needed, parameter update, jirahub-ignore
