Repository spacetelescope/drizzlepac, pull requests merged in 2023-06, with the labels that each got.

#1565 Ensure tweakwcs >= 0.8.2 is in use
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1567 Finalize 360x
  CHANGELOG.rst
  pyproject.toml
  tox.ini
Labels: jirahub-ignore

#1571 Ensure version of Matplotlib <= 3.6.3 for now
  CHANGELOG.rst
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1572 HLA-1029: Fix projection cell identification in overlapping regions
  drizzlepac/haputils/cell_utils.py
Labels: bug, jirahub-ignore

#1600 Newcandidate 361rc1
  CHANGELOG.rst
  drizzlepac/haputils/cell_utils.py
  drizzlepac/minmed.py
Labels: no-changelog-entry-needed, jirahub-ignore, build
