Repository spacetelescope/drizzlepac, pull requests merged in 2023-11, with the labels that each got.

#1693 HLA-1150: MVM failure due to HAPProduct constructor mismatch
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#1695 HLA-1150: MVM failure due to HAPProduct constructor mismatch (#1693)
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/runastrodriz.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1688 Hla 1076 hap intro docs
  doc/source/explanation/hap_introduction.rst
  doc/source/index.rst
  doc/source/reference.rst
  doc/source/reference/astrodrizzle.rst
  doc/source/reference/tweakback.rst
  doc/source/reference/utilfuncs.rst
Labels: Documentation, no-changelog-entry-needed

#1687 pin Python in RTD environment
  doc/.rtd-environment.yml
  doc/source/reference/util.rst
  drizzlepac/haputils/poller_utils.py
Labels: no-changelog-entry-needed

#1698 HLA-1154 Bug fix for processing no_proc_key='WARN'
  drizzlepac/haputils/analyze.py
Labels: bug, no-changelog-entry-needed

#1699 Newcandidate 362rc4
  CHANGELOG.rst
  doc/.rtd-environment.yml
  doc/source/explanation/hap_introduction.rst
  doc/source/index.rst
  doc/source/reference.rst
  doc/source/reference/astrodrizzle.rst
  doc/source/reference/tweakback.rst
  doc/source/reference/util.rst
  doc/source/reference/utilfuncs.rst
  drizzlepac/haputils/analyze.py
  drizzlepac/haputils/poller_utils.py
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1697 Initial setup for ADRs
  doc/ADR_readme.md
  doc/ADRs.md
Labels: enhancement, Documentation, no-changelog-entry-needed, jirahub-ignore

#1709 finalize changelog entry
  CHANGELOG.rst
Labels: jirahub-ignore
