Repository spacetelescope/drizzlepac, pull requests merged in 2024-05, with the labels that each got.

#1795 HLA-1250: Moved test from haputils to drizzlepac/tests
  tests/hap/sample_ipppssoot_flc.fits
  tests/hap/sample_ipppssoot_flt.fits
  tests/hap/sample_ipppssoot_flt_w_skycell_header_keyword.fits
  tests/hap/sample_svm_flc.fits
  tests/hap/sample_svm_flt.fits
  tests/hap/test_processing_utils.py
  tests/hap/test_svm_ibyt50.py
Labels: code cleanup, no-changelog-entry-needed, ready-for-final-review

#1794 ensure extension modules are present in built wheel
  .github/workflows/build.yml
  drizzlepac/__init__.py
  pyproject.toml
  setup.py
Labels: no-changelog-entry-needed

#1797 HLA-1138: Exclude single filter images in the generation of the total detection image
  CHANGELOG.rst
  drizzlepac/haputils/product.py
Labels: feature request, jirahub-ignore

#1800 fix (some) SonarQube issues
  drizzlepac/ablot.py
  drizzlepac/adrizzle.py
  drizzlepac/devutils/comparison_tools/starmatch_hist.py
  drizzlepac/findobj.py
  drizzlepac/hapmultisequencer.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/config_utils.py
  drizzlepac/haputils/starmatch_hist.py
  drizzlepac/imgclasses.py
  drizzlepac/pixreplace.py
  drizzlepac/updatehdr.py
Labels: no-changelog-entry-needed

#1802 HLA-1254: Address issues caught by SonarQube
  CHANGELOG.rst
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/ci_table.py
  drizzlepac/haputils/hapcut_utils.py
  drizzlepac/haputils/product.py
  drizzlepac/nicmosData.py
  drizzlepac/processInput.py
Labels: bug, code cleanup, jirahub-ignore

#1803 change instances of `http` to `https`
  doc/source/conf.py
Labels: no-changelog-entry-needed
