Repository spacetelescope/drizzlepac, pull requests merged in 2024-10, with the labels that each got.

#1892 Added changelog to s_region simplify-polyline improvement.
  CHANGELOG.rst
Labels: jirahub-ignore

#1893 Newcandidate 3711
  CHANGELOG.rst
  drizzlepac/haputils/cell_utils.py
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1891 HLA-1342: Documentation for S_REGION code change
  doc/source/mast_data_products/svm_processing.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1844 HLA-1193/1296/1331: Upgraded all deprecated Photutils calls to accommodate Photutils 1.13.0
  CHANGELOG.rst
  drizzlepac/align.py
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/deconvolve_utils.py
  pyproject.toml
Labels: bug, in progress, testing, code cleanup, jirahub-ignore

#1894 HLA-1284/1287: Properly account for illuminated and non-illuminated pixels
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, in progress, jirahub-ignore

#1903 HLA-1348: Isolate dependencies to optional dependencies list if possible
  pyproject.toml
Labels: no-changelog-entry-needed, annoyance

#1904 HLA-1350/1240: Update background determination algorithm used for producing output source catalogs
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
Labels: enhancement, jirahub-ignore

#1902 HLA-998: Proper handling of files which have SCI extensions completely zero in RAW
  CHANGELOG.rst
  drizzlepac/haputils/analyze.py
  drizzlepac/util.py
Labels: bug, jirahub-ignore

#1905 HLA-1361: Pin github devdep tests to python 3.12
  .github/workflows/ci.yml
Labels: bug, testing, no-changelog-entry-needed, jirahub-ignore
