Repository spacetelescope/drizzlepac, pull requests merged in 2024-07, with the labels that each got.

#1832 HLA-1283: Added drizzlepac animation to the docs
  doc/source/mast_data_products/astrometry.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1834 Testing readthedocs mambaforge versions to fix build failures.
  .readthedocs.yaml
Labels: bug, testing, no-changelog-entry-needed, jirahub-ignore

#1835 Update manageInputCopies to work if input files aren't in working directory
  CHANGELOG.rst
  drizzlepac/processInput.py
Labels: bug

#1837 Renaming archival tests so that they are no longer run daily
  tests/hap/archival_test_alignpipe_randomlist.py
  tests/hap/archival_test_randomlist.py
  tests/hap/archival_test_run_svmpoller.py
Labels: testing, no-changelog-entry-needed, jirahub-ignore

#1840 Upgrade jenkins dev test to python 3.11, fix ci-watson upgrade failures
  JenkinsfileRT
  tests/hap/base_test.py
  tests/hap/test_pipeline.py
  tests/resources.py
Labels: no-changelog-entry-needed, jirahub-ignore

#1842 [Jenkins] fix install conflicts in `3.11-dev` job
  JenkinsfileRT
Labels: bug, no-changelog-entry-needed

#1843 HLA-1269 Testing with Python 3.12
  .github/workflows/ci.yml
  .github/workflows/ci_cron.yml
  CHANGELOG.rst
  JenkinsfileRT
Labels: testing

#1848 HLA-1291: Updated the call to hamming function in deconvolve_utils.py
  CHANGELOG.rst
  drizzlepac/haputils/deconvolve_utils.py
Labels: bug, jirahub-ignore

#1849 Update CHANGELOG.rst
  CHANGELOG.rst
Labels: Documentation, jirahub-ignore

#1847 fix SonarQube issues
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/mapreg.py
Labels: no-changelog-entry-needed, jirahub-ignore

#1851 T2 newcandidate 371rc6
  CHANGELOG.rst
  JenkinsfileRT
  drizzlepac/haputils/deconvolve_utils.py
  tests/hap/base_test.py
  tests/hap/test_pipeline.py
  tests/resources.py
  tox.ini
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1853 HLA-1295: Fixed the computations associated with rejection of catalogs due to cosmic rays
  CHANGELOG.rst
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore

#1854 Newcandidate 371rc7
  CHANGELOG.rst
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1858 HLA-1302: Avoid application of cosmic ray threshold for ACS/SBC and WFC3/IR catalogs
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore

#1859 HLA-1302: Avoid application of cosmic ray threshold for ACS/SBC and WFC3/IR
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
Labels: no-changelog-entry-needed, jirahub-ignore, build
