Repository spacetelescope/drizzlepac, pull requests merged in 2024-02, with the labels that each got.

#1727 HLA-1190: New installation instructions and small text changes
  README.md
  doc/source/drizzlepac_api.rst
  doc/source/getting-started.rst
  doc/source/getting_started/drizzlepac_resources.rst
  doc/source/getting_started/installation.rst
  doc/source/mast_data_products/hap_api.rst
  doc/source/user_reprocessing.rst
  doc/source/user_reprocessing/interactive_image_alignment_tools.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1728 Delete .github/workflows/codesee-arch-diagram.yml
  .github/workflows/codesee-arch-diagram.yml
Labels: no-changelog-entry-needed

#1731 HLA-1203: Bug fix for HCALDP Reunion
  pyproject.toml
Labels: bug, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1736 HLA-1144: Runastrodriz: handle an empty list generated by do_verify_guiding
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed

#1725 HLA-1192: GitHub branch rename master to main
  CHANGELOG.rst
  drizzlepac/haputils/get_git_rev_info.py
Labels: ready-for-final-review

#1730 HLA_1187: Modified the value of "check_big_island_only" to be True even for
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
  tests/hap/test_svm_hrcsbc.py
  tests/hap/test_svm_ibqk07.py
  tests/hap/test_svm_wfc3ir.py
Labels: enhancement, jirahub-ignore

#1737 pyproject.toml specify python_requires >=3.10
  .github/workflows/ci.yml
  .github/workflows/ci_cron.yml
  pyproject.toml
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1743 Numpy version specified as less than 2.0 in pyproject.toml
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore

#1750 Skipping 'number of sources' tests as science tests are not part of t…
  CHANGELOG.rst
  tests/hap/test_svm_wfc3ir.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1749 Modified PyTests (#1748) and fixed conflicts on cherry-pick.
  CHANGELOG.rst
  tests/hap/test_svm_hrcsbc.py
  tests/hap/test_svm_ibqk07.py
  tests/hap/test_svm_wfc3ir.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1729 HLA-993: Adding skycell keyword to pipeline and SVM products
  CHANGELOG.rst
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/cell_utils.py
  drizzlepac/haputils/processing_utils.py
  drizzlepac/haputils/tests/sample_ipppssoot_flc.fits
  drizzlepac/haputils/tests/sample_ipppssoot_flt.fits
  drizzlepac/haputils/tests/sample_ipppssoot_flt_w_skycell_header_keyword.fits
  drizzlepac/haputils/tests/sample_svm_flc.fits
  drizzlepac/haputils/tests/sample_svm_flt.fits
  drizzlepac/haputils/tests/test_processing_utils.py
  drizzlepac/runastrodriz.py
Labels: enhancement, feature request, ready-for-final-review
