Repository spacetelescope/drizzlepac, pull requests merged in 2024-08, with the labels that each got.

#1863 HLA-1307: Commit of updated and final CHANGELOG to 3.7.1x
  CHANGELOG.rst
Labels: jirahub-ignore, build

#1861 [SCSB-170] pin Python<3.13
  pyproject.toml
Labels: no-changelog-entry-needed

#1864 Eliminate Python 3.13 from the target list
  .github/workflows/build.yml
Labels: no-changelog-entry-needed, jirahub-ignore

#1846 HLA-935: Update HDRTAB for MVM products
  CHANGELOG.rst
  drizzlepac/haputils/processing_utils.py
  drizzlepac/haputils/product.py
Labels: enhancement, in progress

#1871 This ticket is just a bit of tightening up of Python code.
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1872 HLA-1315: Fix "finally" block handling Grism/Prism under PyTest
  drizzlepac/hapsequencer.py
  tests/hap/test_svm_j97e06.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore
