Repository spacetelescope/drizzlepac, pull requests merged in 2024-06, with the labels that each got.

#1805 HLA-1257: Remove the use of a custom smoothing kernel for catalog generation
  CHANGELOG.rst
  doc/source/mast_data_products/catalog_generation.rst
  drizzlepac/haputils/catalog_utils.py
Labels: enhancement, jirahub-ignore

#1798 resolve warnings
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
Labels: no-changelog-entry-needed, annoyance

#1809 Manually recovered poller files needed for PyTests
  tests/hap/acs_b37_23_input.out
  tests/hap/test_svm_canary.py
  tests/hap/wfc3_by0_01_input.out
  tests/hap/wfc3_by0_1s_input.out
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1814 Move environment variable declaration into env_vars list
  JenkinsfileRT
Labels: bug, testing

#1815 HLA-1266: Newcandidate Drizzlepac RC - 371rc2
  CHANGELOG.rst
  JenkinsfileRT
Labels: bug, code cleanup, no-changelog-entry-needed, jirahub-ignore, build

#1816 Fixes codecov
  JenkinsfileRT
Labels: bug, testing

#1817 Newcandidate 371rc3 - addresses codecov issues
  JenkinsfileRT
Labels: bug, no-changelog-entry-needed, jirahub-ignore, build

#1818 Newcandidate 371rc4
  conftest.py
  tests/hap/template_svm_demo.py
  tests/hap/test_run_svmpoller.py
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore, build

#1822 Adding pytest-cov to pip install
  JenkinsfileRT
Labels: bug, testing, no-changelog-entry-needed, jirahub-ignore

#1820 HLA-1213: Changes to address proper marking of CRs
  CHANGELOG.rst
  drizzlepac/haputils/hla_flag_filter.py
Labels: bug, jirahub-ignore

#1828 Revert1798 warnings
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
Labels: bug, jirahub-ignore

#1823 HLA-1233: Updated config files to use fitgeom='rshift' and minobj=10
  CHANGELOG.rst
  doc/source/mast_data_products/hap-parameters.rst
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
  tests/hap/test_svm_ibqk07.py
  tests/hap/test_svm_ibyt50.py
Labels: enhancement, ready-for-final-review

#1830 Drizzlepac: Preparation and Tagging of Release Candidate RC5
  CHANGELOG.rst
  JenkinsfileRT
  doc/source/mast_data_products/hap-parameters.rst
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
  pyproject.toml
  tests/hap/test_svm_ibqk07.py
  tests/hap/test_svm_ibyt50.py
Labels: no-changelog-entry-needed, jirahub-ignore, build

#1831 Test for RT, set NumPy<2.0 in dependencies
  pyproject.toml
Labels: no-changelog-entry-needed, jirahub-ignore, investigation, build
