Repository spacetelescope/drizzlepac, pull requests merged in 2024-11, with the labels that each got.

#1907 HLA-1369: No viable data code 0 changed to code 65
  drizzlepac/hapsequencer.py
Labels: no-changelog-entry-needed, ready-for-final-review

#1909 Ignore nans in staticmask call to stsci.imagestats
  drizzlepac/staticMask.py
Labels: bug, no-changelog-entry-needed

#1906 Set devdep github actions tests to python 3.12 (for cron)
  .github/workflows/ci_cron.yml
Labels: bug, testing, ready-for-final-review

#1910 HLA-1370: Fixed a bug from a previous commit for computing statistics
  drizzlepac/haputils/catalog_utils.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1901 HLA-1352: Description of JSON files
  doc/ADRs.md
  doc/source/mast_data_products/hap-parameters.rst
Labels: Documentation

#1911 HLA-1384: Force an exit with a return code, KEYWORD_UPDATE_PROBLEM, in try/exce…
  CHANGELOG.rst
  drizzlepac/hapmultisequencer.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/analyze.py
Labels: bug, jirahub-ignore

#1908 HLA-1362: Modified the minimum RMS computation used as a discriminant for choos…
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
Labels: bug, enhancement, jirahub-ignore
