Repository spacetelescope/drizzlepac, pull requests merged in 2025-05, with the labels that each got.

#2007 HLA-1484: Resolve issue of duplicate IDs in the Total Point Catalog product
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore

#2009 HLA-1482: Force use of Astropy 6.1.7 for Drizzlepac
  CHANGELOG.rst
  pyproject.toml
Labels: jirahub-ignore, investigation

#2014 HLA-1482/HLA-1487: Added parameter setting to the IterativePSFPhotometry call
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
  pyproject.toml
Labels: parameter update, jirahub-ignore

#2017 Merging PR for adding the parameter sub_shape to the IterativePSFPhotometry, circumventing the need to pin astropy
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
  pyproject.toml
Labels: bug

#2019 HLA-1497: Corrected the string comparison to "asn" in the poller_utils.py module
  CHANGELOG.rst
  drizzlepac/haputils/poller_utils.py
Labels: bug

#2024 HLA-1501: Clean-up values (move to proper section or delete) from catalog configuration files
  CHANGELOG.rst
  drizzlepac/devutils/make_cfgobj_files.py
  drizzlepac/devutils/run_config_utils.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Labels: code cleanup

#2026 HLA-1503/HLA-1504: Update the simga values in the catalog configuration files
  CHANGELOG.rst
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Labels: code cleanup, Do Not Merge, parameter update, jirahub-ignore

#2027 HLA-1503: Report correct sigma value for computing threshold for source detection
  CHANGELOG.rst
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
Labels: bug, code cleanup

#2028 HLA-1479: Overwrote the MVM "alignment" configuration files with the SMV files
  CHANGELOG.rst
  drizzlepac/pars/hap_pars/mvm_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
Labels: code cleanup, jirahub-ignore, dependencies

#2029 Merging PRs onto release branch
  CHANGELOG.rst
  drizzlepac/devutils/make_cfgobj_files.py
  drizzlepac/devutils/run_config_utils.py
  drizzlepac/hapsequencer.py
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/poller_utils.py
  drizzlepac/haputils/svm_quality_analysis.py
  drizzlepac/pars/hap_pars/mvm_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Labels: no-changelog-entry-needed, jirahub-ignore
