Repository spacetelescope/drizzlepac, pull requests merged in 2025-07, with the labels that each got.

#2031 HLA-1505: Create PyTest to evaluate Concentration Index (CI) in a Point Catalog
  tests/hap/test_svm_ci.py
Labels: testing, no-changelog-entry-needed, jirahub-ignore

#2045 Update CHANGELOG.rst for the date of release for v3.10.0
  CHANGELOG.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#2047 HLA-1464: Missing IDCSCALE crashes processing
  CHANGELOG.rst
  drizzlepac/runastrodriz.py
Labels: bug, aposteriori
