Repository spacetelescope/drizzlepac, pull requests merged in 2025-03, with the labels that each got.

#1958 HLA-1417: Validation check for WCS solutions from astrometry database
  CHANGELOG.rst
  drizzlepac/runastrodriz.py
Labels: in progress, jirahub-ignore, ready-for-final-review

#1959 HLA-1419: Removal of warnings for photometry_utils.py log of zero of negative number
  CHANGELOG.rst
  drizzlepac/haputils/photometry_tools.py
Labels: annoyance, jirahub-ignore, ready-for-final-review

#1966 Update the Pyproject.toml file to force use of Photutils >= 2.0.0
  CHANGELOG.rst
  pyproject.toml
Labels: jirahub-ignore, build

#1964 HLA_1433: Add clarification comments to IterativePSFPhotometry instantiation
  drizzlepac/haputils/astrometric_utils.py
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore

#1969 HLA-1448: Fix the crfactor designation for the WFPC2 detector to avoid failure
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
  tests/hap/test_svm_u2as01.py
  tests/hap/wfpc2_2as_01_input.out
Labels: bug, jirahub-ignore

#1975 HLA-1237: Removing user facing aspects of TEAL GUI
  CHANGELOG.rst
  doc/source/mast_data_products/reproducing_mast_data_products.rst
  doc/source/user_reprocessing/image_registration.rst
  drizzlepac/__init__.py
  drizzlepac/ablot.help
  drizzlepac/ablot.py
  drizzlepac/acsData.py
  drizzlepac/adrizzle.py
  drizzlepac/align.py
  drizzlepac/buildmask.py
  drizzlepac/buildwcs.py
  drizzlepac/catalogs.py
  drizzlepac/createMedian.py
  drizzlepac/drizCR.py
  drizzlepac/findobj.py
  drizzlepac/imagefindpars.py
  drizzlepac/linearfit.py
  drizzlepac/mapreg.py
  drizzlepac/mdriz.py
  drizzlepac/photeq.py
  drizzlepac/pixreplace.py
  drizzlepac/pixtopix.py
  drizzlepac/pixtosky.py
  drizzlepac/processInput.py
  drizzlepac/refimagefindpars.py
  drizzlepac/resetbits.py
  drizzlepac/sky.help
  drizzlepac/sky.py
  drizzlepac/skytopix.help
  drizzlepac/skytopix.py
  drizzlepac/staticMask.py
  drizzlepac/tweakback.py
  drizzlepac/tweakreg.py
  drizzlepac/updatenpol.py
  drizzlepac/util.py
Labels: code cleanup

#1978 HLA-1441: Tune Point Catalogs (too many false detections)
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/haputils/hla_flag_filter.py
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Labels: enhancement, code cleanup, jirahub-ignore

#1979 Moved hla_flag_filter_HLAClassic.py into devutils subdirectory
  drizzlepac/devutils/hla_flag_filter_HLAClassic.py
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1980 Updated the MVM ACS/WFC quality control JSON file
  drizzlepac/pars/hap_pars/mvm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/acs/wfc/acs_wfc_quality_control_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/mvm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Labels: code cleanup, no-changelog-entry-needed, jirahub-ignore

#1967 HLA-1425: Documenting the Alignment Logic
  CHANGELOG.rst
  doc/source/mast_data_products/pipeline-astrometric-calibration-description.rst
  doc/source/mast_data_products/svm_processing.rst
Labels: Documentation, ready-for-final-review

#1987 Dropping support for python 3.10
  .github/workflows/ci.yml
  CHANGELOG.rst
  pyproject.toml
Labels: jirahub-ignore

#1992 Fix for I/O astrometry database bug
  drizzlepac/__init__.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1993 Updated CHANGELOG.rst
  CHANGELOG.rst
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore
