Repository spacetelescope/drizzlepac, pull requests merged in 2025-04, with the labels that each got.

#2000 Remove duplicated log lines from dependencies in runastrodriz
  drizzlepac/runastrodriz.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1976 HLA-705: Reproduce trailer file using logger
  drizzlepac/__init__.py
  drizzlepac/runastrodriz.py
Labels: ready-for-final-review

#1999 HLA-1465: Added documentation photometry discussion of the source catalog products
  doc/source/mast_data_products/catalog_generation.rst
Labels: Documentation

#2005 Reverting EXPFLAG change from PR #1968
  CHANGELOG.rst
  drizzlepac/haputils/analyze.py
Labels: bug
