Repository spacetelescope/drizzlepac, pull requests merged in 2025-01, with the labels that each got.

#1928 Truncate pytest failure report for ascii diffs
  tests/resources.py
Labels: bug, no-changelog-entry-needed, jirahub-ignore, ready-for-final-review

#1929 HLA-1402: Fix failing pytests
  .github/pull_request_template.md
  doc/source/mast_data_products/hap-parameters.rst
  tests/acs/test_asn_regress.py
  tests/hap/test_align.py
Labels: testing, no-changelog-entry-needed, ready-for-final-review

#1933 HLA-1406: Truth files saved to correct location on artifactory
  CHANGELOG.rst
  tests/resources.py
Labels: enhancement, testing, ready-for-final-review

#1931 Pins drizzlepac to the most recent STWCS version that also requires numpy>2.0
  pyproject.toml
Labels: ready-for-final-review, dependencies

#1934 HLA-1410/HLA-1393: Drizzlepac/HAP: Round 2 update of improved Photutils deprecation updates
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/product.py
  tests/hap/test_svm_ibqk07.py
Labels: bug, in progress, Do Not Merge, jirahub-ignore

#1941 Update testing information on README.md
  README.md
Labels: Documentation, no-changelog-entry-needed, jirahub-ignore
