Repository spacetelescope/drizzlepac, pull requests merged in 2025-02, with the labels that each got.

#1939 HLA-1407: Implemented fixes to address uneven detection thresholds in HAP catalogs
  CHANGELOG.rst
  drizzlepac/haputils/catalog_utils.py
Labels: bug, jirahub-ignore

#1932 HLA-1405: Updated alignment parameters.
  CHANGELOG.rst
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_alignment_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_alignment_all.json
  tests/hap/test_svm_ibyt50.py
Labels: parameter update, ready-for-final-review

#1951 Revert build workflow back to using python 3.12
  .github/workflows/build.yml
Labels: bug, no-changelog-entry-needed, jirahub-ignore

#1950 HLA-1413: Replaced deprecated class
  CHANGELOG.rst
  drizzlepac/haputils/astrometric_utils.py
Labels: enhancement, jirahub-ignore

#1953 HLA-1427: Improve algorithm for switching to crowded field kernel for HAP segment catalogs
  CHANGELOG.rst
  doc/source/mast_data_products/catalog_generation.rst
  drizzlepac/haputils/catalog_utils.py
  drizzlepac/pars/hap_pars/svm_parameters/acs/hrc/acs_hrc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/sbc/acs_sbc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/acs/wfc/acs_wfc_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/ir/wfc3_ir_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfc3/uvis/wfc3_uvis_catalog_generation_all.json
  drizzlepac/pars/hap_pars/svm_parameters/wfpc2/pc/wfpc2_pc_catalog_generation_all.json
Labels: enhancement, jirahub-ignore

#1936 HLA-1412: Get regression tests to pass with python 3.13
  .github/workflows/ci.yml
  CHANGELOG.rst
  drizzlepac/updatehdr.py
  drizzlepac/util.py
  pyproject.toml
Labels: testing, ready-for-final-review

#1957 HLA-1433: Remove parameter deprecated in Photutils 2.0
  CHANGELOG.rst
  drizzlepac/haputils/align_utils.py
  drizzlepac/haputils/astrometric_utils.py
  drizzlepac/haputils/catalog_utils.py
Labels: parameter update, jirahub-ignore
